hack/boilerplate/boilerplate.Dockerfile.txt, hack/boilerplate/boilerplate.Makefile.txt, hack/boilerplate/boilerplate.bzl.txt, hack/boilerplate/boilerplate.go.txt, hack/boilerplate/boilerplate.py, hack/boilerplate/boilerplate.py.txt, hack/boilerplate/boilerplate.sh.txt, hack/verify-all.sh, hack/verify-boilerplate.sh, pkg/blobfuseplugin/Dockerfile, test/integration/run-test.sh
> /kind cleanup
Add boilerplate check.
Fixes #8 
```
None
```
=> add boilerplate check

pkg/blobfuse/controllerserver.go
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind flake
/kind bug
Fixes #
```
fix sanity test DeleteVolume failure
fix sanity test ValidateVolumeCapabilities failure
```
=> fix sanity test failures, DeleteVolume and ValidateVolumeCapabilities

pkg/blobfuse/azure.go, pkg/blobfuse/controllerserver.go, pkg/blobfuse/nodeserver.go
/kind cleanup
Fixes #
```
none
```
=> use cloud.GetStorageAccesskey instead

pkg/blobfuse/controllerserver.go, pkg/blobfuse/nodeserver.go, pkg/util/util.go, pkg/util/util_test.go
/kind feature
Fixes #25 
Fixes #30
```
add mountOptions and readOnly support
```
=> add mountOptions and readOnly support

test/integration/run-test.sh
/kind cleanup
Fixes #
```
none
```
=> refactor of integration test

.travis.yml, Makefile, test/sanity/README.md, test/sanity/run-tests-all-clouds.sh
/kind design
Fixes #
```
chore: enable sanity test in CI
```
=> chore: enable sanity test in CI

test/sanity/run-tests-all-clouds.sh
=> chore: fix mount sanity test failure

test/integration/run-test.sh
=> enable mount/unmount CI test

test/integration/run-test.sh
=> test: randomize volume name

.travis.yml, Makefile, test/integration/run-test.sh, test/integration/run-tests-all-clouds.sh, test/sanity/run-tests-all-clouds.sh
fix travis ci config
Fixes #
```
none
```
=> test: refactor test infra

pkg/blobfuse/blobfuse.go, pkg/blobfuse/blobfuse_test.go, pkg/blobfuse/controllerserver.go
Before creating container, we need to set container name as volume name.
>
> /kind bug
Fixes #28 #34 
```
fix: set container name as volume name
```
=> fix: set container name as volume name

.travis.yml, test/sanity/run-test.sh, test/sanity/run-tests-all-clouds.sh
/kind flake
skip unnecessary sanity tests.
Now sanity tests are totally credible.
Fixes #28 
```
none
```
=> chore: skip unnecessary sanity tests

Gopkg.lock, pkg/blobfuse/controllerserver.go
/kind bug
Add retry for DeleteVolume. Since it's a 409 error, it should retry
Fixes #47 
```
add retry for DeleteVolume
```
=> fix: add retry for DeleteVolume

test/e2e/dynamic_provisioning.go, test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
/kind test
add e2e test "dynamically_provisioned_read_only_volume"
Fixes #
```
add e2e test "dynamically_provisioned_read_only_volume"
```
=> test: add e2e test "dynamically_provisioned_read_only_volume"

test/e2e/pre_provisioning.go, test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/testsuites.go
/kind test
add e2e test "pre_provisioned_reclaim_policy"
Fixes #
```
add e2e test "pre_provisioned_reclaim_policy"
```
=> test: add e2e test "pre_provisioned_reclaim_policy"

test/e2e/pre_provisioning.go, test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
/kind test
add e2e test "pre_provisioned_read_only_volume"
Fixes #
```
add e2e test "pre_provisioned_read_only_volume"
```
=> test: add e2e test "pre_provisioned_read_only_volume"

test/e2e/dynamic_provisioning.go, test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
/kind test
add e2e test "dynamically_provisioned_collocated_pod"
Fixes #
```
add e2e test "dynamically_provisioned_collocated_pod"
```
=> test: add e2e test "dynamically_provisioned_collocated_pod"

test/e2e/dynamic_provisioning.go, test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
/kind test
add e2e test "dynamically_provisioned_reclaim_policy_test"
Fixes #
```
add e2e test "dynamically_provisioned_reclaim_policy_test"
```
=> test: add e2e test "dynamically_provisioned_reclaim_policy_test"

README.md, deploy/v0.2.0/crd-csi-driver-registry.yaml, deploy/v0.2.0/crd-csi-node-info.yaml, deploy/v0.2.0/csi-blobfuse-controller.yaml, deploy/v0.2.0/csi-blobfuse-node.yaml, deploy/v0.2.0/rbac-csi-blobfuse-controller.yaml, docs/install-blobfuse-csi-driver.md, docs/install-csi-driver-master.md, docs/install-csi-driver-v0.2.0.md
chore: cut off v0.2.0 beta release
Fixes #
```
none
```
=> chore: cut off v0.2.0 beta release

deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml, deploy/v0.1.0/csi-blobfuse-controller.yaml, deploy/v0.1.0/csi-blobfuse-node.yaml, deploy/v0.2.0/csi-blobfuse-controller.yaml, deploy/v0.2.0/csi-blobfuse-node.yaml
/kind feature
Fixes #65 
```
set priority class to system critical
```
=> feat: set priority class to system critical

pkg/blobfuse/blobfuse.go, pkg/blobfuse/blobfuse_test.go, pkg/blobfuse/nodeserver.go
/kind feature
Currently, blobfuse supports SAS token, we could add SAS token support in static provisioning scenario
Fixes #37 
```
add SAS token support
```
=> feat: add SAS token support

deploy/uninstall-driver.sh, test/e2e/dynamic_provisioning.go, test/e2e/pre_provisioning.go
/kind test
test: change csi.sock to fix random e2e test failure
Fixes #
```
none
```
=> test: change csi.sock to fix random e2e test failure

deploy/example/keyvault/README.md, deploy/example/keyvault/pv-blobfuse-csi-keyvault.yaml, deploy/example/keyvault/pvc-blobfuse-csi-static-keyvault.yaml, docs/driver-parameters.md
add the example of using key vault
Fixes #69 
```
add the example of using key vault
```
=> docs: add the example of using key vault

.travis.yml, CHANGELOG-v0.1.0-alpha.md, Makefile, README.md, charts/README.md, docs/csi-dev.md, docs/read-from-keyvault.md, pkg/blobfuse/blobfuse.go, pkg/blobfuse/controllerserver.go, pkg/blobfuseplugin/main.go, test/e2e/driver/blobfuse_csi_driver.go, test/e2e/dynamic_provisioning.go, test/e2e/pre_provisioning.go, test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go, test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go, test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go, test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/specs.go, test/e2e/testsuites/testsuites.go, test/sanity/sanity_test.go
/kind cleanup
chore: fix repo org name change
Fixes #
```
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" *.md
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" ./charts/*.md
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" Makefile
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" ./test/sanity/*.go
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" ./test/e2e/driver/*.go
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" pkg/blobfuse/*.go
sed -i "s/github.com\/csi-driver/github.com\/kubernetes-sigs/g" ./test/e2e/testsuites/*.go
sed -i …
```
=> chore: fix repo org name change

OWNERS, OWNERS_ALIASES
/kind cleanup
chore: update owners
Fixes #83
```
none
```
=> chore: update owners

docs/driver-parameters.md, docs/read-from-keyvault.md, hack/verify-all.sh, hack/verify-spelling.sh, pkg/blobfuse/blobfuse.go, pkg/util/util.go
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind flake
Enable spell checking and fix spelling issues.
Fixes #
```
NONE
```
=> Enable spell checking and fix spelling issues

Makefile, charts/README.md, docs/csi-dev.md, pkg/blobfuse/blobfuse.go, pkg/blobfuse/controllerserver.go, pkg/blobfuseplugin/main.go, test/e2e/driver/blobfuse_csi_driver.go, test/e2e/dynamic_provisioning.go, test/e2e/pre_provisioning.go, test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go, test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go, test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go, test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/specs.go, test/e2e/testsuites/testsuites.go, test/integration/integration_test.go, test/sanity/sanity_test.go, test/utils/credentials/credentials.go
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind flake
With blobfuse-csi-driver migrated to kubernetes-sigs org, we should change the package prefix from `github.com/kubernetes-sigs` to `sigs.k8s.io`. This PR is necessary 
Related issue: https://github.com/kubernetes-sigs/blobfuse-csi-driver/issues/9
```
None.
```
=> s|github.com/kubernetes-sigs|sigs.k8s.io

.gitignore, charts/README.md, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/values.yaml, deploy/csi-blobfuse-controller.yaml, deploy/rbac-csi-blobfuse-controller.yaml
- Settings are adapted from kubernetes-sigs/azuredisk-csi-driver#224
- Refactored chart image references
>
/kind feature
Fixes #
```
```
=> Enable leader election in csi components

pkg/blobfuse/blobfuse.go, pkg/blobfuse/nodeserver.go, pkg/blobfuse/nodeserver_test.go, test/e2e/suite_test.go, test/integration/run-test.sh, test/integration/run-tests-all-clouds.sh, test/utils/blobfuse_log.sh
/kind feature
feat: use NodeStageVolume, so that one PV could be accessed by multiple pods on one node
Fixes #91
```
feat: use NodeStageVolume
```
=> feat: use NodeStageVolume

charts/latest/blobfuse-csi-driver/values.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml, pkg/blobfuse/nodeserver.go
/kind cleanup
feat: swtich to use mcr repo
Fixes #
```
none
```
=> chore: swtich to use mcr repo

charts/latest/blobfuse-csi-driver/values.yaml, deploy/csi-blobfuse-controller.yaml
/kind feature
set smaller replica(2 by default) for controller
Fixes #
```
none
```
=> chore: set smaller replica

docs/install-csi-driver-master.md, docs/install-csi-driver-v0.1.0.md, docs/install-csi-driver-v0.2.0.md, docs/install-csi-driver-v0.3.0.md, docs/install-csi-driver-v0.4.0.md
doc: fix doc typo
Fixes #
```
none
```
=> doc: fix doc typo

.travis.yml, README.md
/kind flake
fix broken Coverage
Fixes #
```
```
=> chore: fix broken coverage

test/e2e/dynamic_provisioning_test.go, test/e2e/pre_provisioning_test.go, test/e2e/suite_test.go, test/utils/check_driver_pods_restart.sh
/kind flake
add a pod restart check in the e2e test, to make sure there is no pod restart during e2e test, if there is pod restart, e2e test should fail
Fixes #
```
```
=> chore: add driver pods check

deploy/example/pv-blobfuse-csi.yaml, docs/driver-parameters.md
doc: use nodeStageSecretRef instead of nodePublishSecretRef
Fixes #
```
none
```
=> doc: use nodeStageSecretRef instead of nodePublishSecretRef

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/crd-csi-driver-registry.yaml, deploy/crd-csi-node-info.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml, deploy/rbac-csi-blobfuse-controller.yaml, hack/verify-all.sh, hack/verify-yamllint.sh, pkg/blobfuseplugin/main.go
/kind feature
This PR adds yaml format check and also changed port num
controller
health: 29622
metrics: 29624
node
health: 29623
Fixes #
```
none
```
=> change port num

deploy/uninstall-driver.sh, hack/verify-yamllint.sh
/kind cleanup
chore: fix some scripts
Fixes #
```
none
```
=> chore: fix some scripts

deploy/example/nginx-pod-blobfuse.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pvc-blobfuse-csi-static.yaml, deploy/example/pvc-blobfuse-csi.yaml, deploy/example/storageclass-blobfuse-csi-existing-container.yaml, deploy/example/storageclass-blobfuse-csi-mountoptions.yaml, deploy/example/storageclass-blobfuse-csi.yaml, hack/verify-yamllint.sh, pkg/blobfuse/nodeserver.go
doc: fix yaml format
Fixes #
```
sed -i '1i\---' deploy/example/*.yaml
```
```
none
```
=> doc: fix yaml format

pkg/blobfuse/nodeserver.go, test/sanity/run-tests-all-clouds.sh
/kind bug
/kind flake
In CSI Spec, it requires that the SP MUST delete the file or directory it created at this path.
Ref: https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunpublishvolume
Fixes #
```
```
=> fix: correct the behavior of deleting the target direcotory

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, charts/v0.4.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/v0.4.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml, deploy/v0.1.0/csi-blobfuse-controller.yaml, deploy/v0.1.0/csi-blobfuse-node.yaml, deploy/v0.2.0/csi-blobfuse-controller.yaml, deploy/v0.2.0/csi-blobfuse-node.yaml, deploy/v0.3.0/csi-blobfuse-controller.yaml, deploy/v0.3.0/csi-blobfuse-node.yaml, deploy/v0.4.0/csi-blobfuse-controller.yaml, deploy/v0.4.0/csi-blobfuse-node.yaml
/kind cleanup
Ref: kubernetes/kubernetes#89477
Fixes #
```
```
=> chore: replace beta label to GA label for kubernetes.io/os

deploy/install-driver.sh, deploy/uninstall-driver.sh, docs/install-csi-driver-master.md
doc: refine installation scripts
Fixes #
```
none
```
=> doc: refine installation scripts

deploy/install-driver.sh, deploy/uninstall-driver.sh, test/e2e/suite_test.go
/kind test
test: add install/uninstall deployment script test 
Fixes #
```
none
```
=> test: add install/uninstall deployment script test

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml
/kind bug
fix: set cpu,memory limit to a higher value
Fixes #
```
fix: set cpu,memory limit to a higher value
```
=> fix: set cpu,memory limit to a higher value

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-secret.yaml, charts/latest/blobfuse-csi-driver/templates/serviceaccount-csi-blobfuse-node.yaml, deploy/csi-blobfuse-node.yaml, deploy/install-driver.sh, deploy/rbac-csi-blobfuse-controller.yaml, deploy/rbac-csi-blobfuse-node.yaml, deploy/uninstall-driver.sh, docs/read-from-secret.md, pkg/blobfuse/azure.go, pkg/blobfuse/azure_test.go, pkg/blobfuse/blobfuse.go, pkg/blobfuseplugin/main.go, test/e2e/suite_test.go
/kind feature
/kind flake
- read cloud config from secret 
- update the related deployment
- add the related doc
Fixes #130 
```
read cloud config from secret 
```
=> feat: read cloud config from secret

deploy/install-driver.sh, deploy/rbac-csi-blobfuse-secret.yaml, deploy/uninstall-driver.sh
/kind flake
add secret rbac file in deploy directory.
Fixes #
```
```
=> chore: add secret rbac file

hack/verify-golint.sh, hack/verify-yamllint.sh
/kind test
Fixes #
```
none
```
=> fix golint issue

pkg/blobfuse/nodeserver.go
/kind feature
feat: add sovereign cloud support
And also needs to update blobfuse binary(latest: `v1.2.1`) in blobfuse driver image
Fixes #39
```
feat: add sovereign cloud support
```
=> feat: add sovereign cloud support

README.md, docs/read-from-secret.md
doc: update read from secret doc
Fixes #
```
none
```
=> doc: update read from secret doc

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml, hack/verify-yamllint.sh, pkg/blobfuse/blobfuse.go, pkg/blobfuse/controllerserver.go
/kind feature
feat: disable IMDS in controller to support MSI
Fixes #109
```
feat: disable IMDS in controller to support MSI
```
=> feat: disable IMDS in controller to support MSI

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml
/kind feature
chore: lower the cpu/memory limits
Fixes #
```
none
```
=> chore: lower the cpu/memory limits

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/rbac-csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/values.yaml, deploy/csi-blobfuse-controller.yaml, deploy/rbac-csi-blobfuse-controller.yaml
/kind feature
chore: upgrade csi-attacher to v2.2.0
Fixes #
```
none
```
=> chore: upgrade csi-attacher to v2.2.0

deploy/example/e2e_usage.md, deploy/example/pv-blobfuse-csi.yaml
doc: Delete policy is not supported in static provisioning
Fixes #135
cc @raushan2016
```
none
```
=> doc: Delete policy is not supported in static provisioning

deploy/example/pv-blobfuse-csi.yaml, hack/verify-spelling.sh
doc: add mountOptions
Fixes #
```
none
```
=> doc: add mountOptions

README.md, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml
/kind feature
feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
> To specify a different cloud provider config file, create `azure-cred-file` configmap before driver installation, e.g. for OpenShift, it's `/etc/kubernetes/cloud.conf`
> ```console
> kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" --from-literal=path-windows="C:\\k\\cloud.conf" -n kube-system
> ```
Fixes #
```
feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
```
=> feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path

charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-driver.yaml, deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-driver.yaml
/kind bug
fix: broken config(missing endpoint) in controller deployment
`--endpoint` is missing in controller deployment, makes controller crash and fail to provision a blobfuse PVC.
Fixes #
```
fix: broken config(missing endpoint) in controller deployment
```
=> fix: broken config(missing endpoint) in controller deployment

charts/v0.5.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml, deploy/v0.5.0/csi-blobfuse-controller.yaml
/kind bug
fix: endpoint issue in v0.5.0
Fixes #
```
fix: endpoint issue in v0.5.0
```
=> fix: endpoint issue in v0.5.0

deploy/example/pv-blobfuse-csi.yaml, deploy/example/storageclass-blobfuse-csi-mountoptions.yaml, deploy/example/storageclass-blobfuse-csi.yaml, docs/driver-parameters.md, pkg/blobfuse/controllerserver.go, test/e2e/driver/blobfuse_csi_driver.go, test/e2e/dynamic_provisioning_test.go, test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go, test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go, test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/specs.go
/kind test
/kind feature
This PR:
- add Premium_LRS support
- add more storage account types in e2e tests
Fixes #
```
feat: add Premium_LRS support
```
=> feat: add Premium_LRS support

.github/PULL_REQUEST_TEMPLATE.md, pkg/blobfuse/controllerserver.go, test/e2e/dynamic_provisioning_test.go, test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go, test/e2e/testsuites/specs.go
/kind test
test: add pod with multiple volumes mount e2e test
Fixes #
```
none
```
=> test: add pod with multiple volumes mount e2e test

deploy/example/pv-blobfuse-csi.yaml, pkg/blobfuse/nodeserver.go
/kind bug
fix: remove secret logging in NodeStageVolume
Fixes #
```
none
```
=> fix: remove secret logging in NodeStageVolume

deploy/example/deployment.yaml, deploy/example/e2e_usage.md, deploy/example/pvc-blobfuse-csi.yaml, deploy/example/storageclass-blobfuse-csi-existing-container.yaml, deploy/example/storageclass-blobfuse-csi-mountoptions.yaml, deploy/example/storageclass-blobfuse-csi.yaml
doc: rename storage class to blob
Fixes #
```
none
```
=> doc: rename storage class to blob

test/e2e/dynamic_provisioning_test.go
/kind test
test: add mount options test
Fixes #
```
none
```
=> test: add mount options test

pkg/blobfuseplugin/Dockerfile
=> update blobfuseplugin base image with debian-base.

.travis.yml, pkg/blobfuse/blobfuse_test.go, pkg/blobfuse/controllerserver_test.go, pkg/blobfuse/identityserver_test.go, pkg/blobfuse/nodeserver.go, pkg/blobfuse/nodeserver_test.go, pkg/blobfuse/version_test.go, pkg/csi-common/controllerserver-default_test.go
/kind test
Fixes #151 
```
none
```
=> test: add unit-test

deploy/install-driver.sh
/kind bug
fix: installation issue
Fixes #
```
none
```
=> fix: installation issue

hack/release-image.sh
/kind test
chore: add hack/release-image.sh
Fixes #
```
none
```
=> chore: add hack/release-image.sh

.travis.yml, Makefile, deploy/install-driver.sh, deploy/uninstall-driver.sh, pkg/blobfuseplugin/dev.Dockerfile
/kind test
test: add dev.Dockerfile
Fixes #
```
none
```
=> test: add dev.Dockerfile

hack/verify-all.sh, hack/verify-gomod.sh, pkg/util/util_test.go
/kind test
Fixes #181 
```
none
```
=> test: add hack/verify-gomod.sh

deploy/csi-blobfuse-controller.yaml, deploy/csi-blobfuse-node.yaml, hack/release-image.sh
/kind cleanup
chore: set default imagePullPolicy
Actually default value of `imagePullPolicy` is `IfNotPresent`, this PR does not change anything, only make user easier to change that value to `Always` if user wants update latest version
Fixes #
```
none
```
=> chore: set default imagePullPolicy

deploy/example/statefulset.yaml, pkg/blobfuse/nodeserver_test.go
/kind test
test: remove syscall due to build failure(`go test`) on Windows
Fixes #
cc @Sakuralbj 
```
none
```
=> test: remove syscall due to build failure on Windows

go.mod, pkg/blobfuse/controllerserver_test.go, pkg/csi-common/controllerserver-default_test.go, vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/doc.go, vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/interface.go, vendor/modules.txt
…ollerserver-default.
/kind test
Fixes #
```
none
```
=> test: add unit-test in blobfuse/controllerserver and csi-common/con-default

deploy/example/storageclass-blob-nfs.yaml, pkg/blobfuse/blobfuse.go, pkg/blobfuse/blobfuse_test.go, pkg/blobfuse/controllerserver.go, pkg/blobfuse/controllerserver_test.go, pkg/blobfuse/nodeserver.go, pkg/blobfuseplugin/Dockerfile, pkg/blobfuseplugin/dev.Dockerfile
/kind feature
feat: support [blob storage based NFS](https://docs.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to)
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: blob
provisioner: blobfuse.csi.azure.com
parameters:
storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
protocol: nfs
volumeBindingMode: Immediate
```
Fixes #
```
support blob storage based NFS
```
=> feat: support blob storage based NFS

README.md, deploy/example/nfs/README.md
doc: add NFSv3 support doc
Fixes #
```
none
```
=> doc: add NFSv3 support doc

README.md, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-driver.yaml, charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml, deploy/csi-blobfuse-driver.yaml, deploy/csi-blobfuse-node.yaml, deploy/example/e2e_usage.md, deploy/example/nfs/README.md, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/storageclass-blob-nfs.yaml, deploy/example/storageclass-blobfuse-csi-existing-container.yaml, deploy/example/storageclass-blobfuse-csi-mountoptions.yaml, deploy/example/storageclass-blobfuse-csi.yaml, docs/csi-dev.md, pkg/blobfuse/blobfuse.go
/kind feature
chore: rename driver name "blob.csi.azure.com"
Fixes #
```
chore: rename driver name "blob.csi.azure.com"
```
=> chore: rename driver name "blob.csi.azure.com"

README.md, RELEASE.md, charts/README.md, charts/latest/blobfuse-csi-driver/templates/NOTES.txt, deploy/install-driver.sh, deploy/uninstall-driver.sh, docs/csi-dev.md, docs/design.md, docs/install-blobfuse-csi-driver.md, docs/install-csi-driver-master.md, docs/read-from-keyvault.md, pkg/blobfuseplugin/Dockerfile, pkg/blobfuseplugin/dev.Dockerfile, pkg/blobfuseplugin/main.go, test/e2e/suite_test.go, test/utils/credentials/credentials.go
doc: rename driver as "Azure Blob Storage CSI driver"
Fixes #
```
doc: rename driver as "Azure Blob Storage CSI driver"
```
=> doc: rename driver as "Azure Blob Storage CSI driver"

Makefile, pkg/blob/azure.go, pkg/blob/azure_test.go, pkg/blob/blobfuse.go, pkg/blob/blobfuse_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/identityserver.go, pkg/blob/identityserver_test.go, pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go, pkg/blob/version.go, pkg/blob/version_test.go, pkg/blobplugin/Dockerfile, pkg/blobplugin/main.go, test/e2e/driver/blobfuse_csi_driver.go, test/e2e/dynamic_provisioning_test.go, test/e2e/pre_provisioning_test.go, test/e2e/suite_test.go, test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go, test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go, test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go, test/e2e/testsuites/testsuites.go
rename test failure
/kind feature
chore: rename driver
Fixes #
```
none
```
=> chore: rename driver

charts/README.md, charts/latest/blobfuse-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blobfuse-csi-driver/templates/rbac-csi-blob-controller.yaml, charts/latest/blobfuse-csi-driver/templates/serviceaccount-csi-blob-controller.yaml, deploy/csi-blob-controller.yaml, deploy/example/metrics/README.md, deploy/example/metrics/csi-blob-controller-svc.yaml, deploy/install-driver.sh, deploy/rbac-csi-blob-controller.yaml, deploy/uninstall-driver.sh, docs/csi-debug.md, docs/install-csi-driver-master.md, hack/verify-helm-chart.sh, test/utils/blob_log.sh
/kind feature
chore: rename controller
Fixes #
```
none
```
=> chore: rename controller

docs/driver-parameters.md, pkg/blob/blobfuse.go, pkg/blob/blobfuse_test.go, pkg/blob/controllerserver.go
/kind bug
fix: use new naming rule for nfs container
Fixes #
```
fix: use new naming rule for nfs container
```
=> fix: use new naming rule for nfs container

charts/index.yaml
=> docs: add blobfuse-v0.6.0 information in index.yaml

Makefile, charts/latest/blobfuse-csi-driver/Chart.yaml, charts/latest/blobfuse-csi-driver/values.yaml, deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml, hack/release-image.sh
/kind feature
chore: rename driver image
Fixes #
```
none
```
=> chore: rename driver image

README.md, deploy/example/deployment.yaml, deploy/example/e2e_usage.md, deploy/example/nginx-pod-blob.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pvc-blob-csi-static.yaml, deploy/example/pvc-blob-csi.yaml, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, test/e2e/dynamic_provisioning_test.go, test/e2e/pre_provisioning_test.go, test/e2e/suite_test.go, test/e2e/testsuites/testsuites.go, test/utils/check_driver_pods_restart.sh
/kind test
chore: rename driver tests
Fixes #
```
none
```
=> chore: rename driver tests

pkg/blob/controllerserver.go
/kind bug
fix: set correct account prefix for NFS protocol
Fixes #
```
fix: set correct account prefix for NFS protocol
```
=> fix: set correct account prefix for NFS protocol

deploy/example/deployment.yaml, deploy/example/e2e_usage.md, docs/design.md
doc: renaming in doc
Fixes #
```
none
```
=> doc: renaming in doc

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver_test.go, pkg/blobplugin/main.go, pkg/csi-common/server.go, pkg/csi-common/server_test.go, pkg/csi-common/utils.go, test/e2e/suite_test.go
/kind test
Fixes #
```
none
```
=> test: add unit-test in pkg/blob and server

pkg/blob/fake_mount.go, pkg/blob/fake_mount_test.go, pkg/blob/nodeserver_test.go, pkg/csi-common/driver_test.go, pkg/csi-common/identityserver-default_test.go, pkg/csi-common/utils_test.go
/kind test
Fixes #151 
```
none
```
=> test: add unit-test in nodeserver and csi-common.

pkg/blob/azure_test.go, pkg/blob/controllerserver_test.go, pkg/blob/fake_mount.go, pkg/blob/fake_mount_test.go, pkg/blob/nodeserver_test.go, pkg/csi-common/utils_test.go
/kind test
Fixes #151 
```
none
```
=> test: add unit-test in pkg/blob and pkg/csi-common.

charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml, deploy/example/metrics/README.md, deploy/example/metrics/csi-blob-controller-svc.yaml
doc: port num change due to driver rename
change port num so `blobfuse.csi.azure.com` and `blob.csi.azure.com` drivers would coexist in one cluster.
Fixes #
```
none
```
=> doc: port num change due to driver rename

pkg/blobplugin/Dockerfile
/kind bug
fix: nfs protocol not supported issue
Fixes #
```
fix: nfs protocol not supported issue
```
=> fix: nfs protocol not supported issue

deploy/example/deployment.yaml, deploy/example/nginx-pod-blob.yaml, deploy/example/statefulset.yaml
chore: add linux tag for linux deployment
Fixes #
```
none
```
=> chore: add linux tag for linux deployment

charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, deploy/csi-blob-node.yaml
/kind bug
chore: adjust cpu/memory limit for blob node pod
- context
blobfuse driver could take up to 2GB of RAM to run, so we set as `2100Mi` in this PR
paste some resource usage data:
```
blobfuse:
Container ID:  docker://f3234751ef0b0392cf5a4427295afeafa950a0d8f511b4d44a77b69b16398926
Image:         mcr.microsoft.com/k8s/csi/blobfuse-csi:v0.5.0
Image ID:      docker-pullable://mcr.microsoft.com/k8s/csi/blobfuse-csi@sha256:00171d0ad40191e3e577f3d5a67820f0b03849037536759a58a502522dd17893
Ports:         29623/TCP, 29625/TCP
Host Ports:    29623/TCP, 29625/TCP
Args:
--v=5
--endpoint=$(CSI_ENDPOINT)
--nodeid=$(KUBE_NODE_NAME)
--metrics-address=0.0.0.0:29625
State:          Running
Started:      Sun, 09 Aug 2020 21:41:54 …
```
=> chore: adjust cpu/memory limit for blob node pod

charts/README.md, charts/latest/blob-csi-driver/templates/_helpers.tpl, charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
/kind feature
Addressing [494](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/494)
Fixes #
```
fix: add imagePullSecretsin Helm chart for secret used to pull Docker images
```
=> fix: add imagePullSecretsin Helm chart for secret used to pull Docker images

deploy/example/metrics/csi-blob-controller-svc.yaml, docs/csi-debug.md, hack/verify-yamllint.sh, test/manifest/linux.json, test/utils/blob_log.sh
/kind cleanup
/kind test
test: run e2e test on containerd
Fixes #
```
none
```
=> test: run e2e test on containerd

deploy/example/e2e_usage.md
Clarify scope of parameters to avoid users passing resource ids instead of names
=> Clarify scope of parameters

.github/PULL_REQUEST_TEMPLATE.md, deploy/example/e2e_usage.md, deploy/example/storageclass-blobfuse-existing-container.yaml, deploy/example/storageclass-blobfuse-msi.yaml, deploy/example/storageclass-blobfuse-readonly.yaml
doc: fix example docs
Fixes #
```
none
```
=> doc: fix example docs

Makefile, charts/README.md, charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-controller.yaml, deploy/example/metrics/README.md, deploy/example/metrics/csi-blob-controller-svc.yaml, pkg/blobplugin/main.go, test/e2e/suite_test.go, test/utils/blob_log.sh
/kind bug
fix: metrics port and doc issue
Fixes #
```
fix: metrics port and doc issue
```
=> fix: metrics port and doc issue

Makefile
Signed-off-by: Ernest Wong <chuwon@microsoft.com>
/kind cleanup
/assign @andyzhangx 
Fixes #
```
none
```
=> ci: allow override of IMAGE_TAG and E2E_HELM_OPTIONS in Makefile

pkg/blobplugin/Dockerfile
/kind bug
Update debian base image to v2.1.3 to address CVEs.
Fixes #
```
fix: Update debian base image to v2.1.3
```
=> fix: Update debian base image to v2.1.3

charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, deploy/csi-blob-controller.yaml, deploy/example/deployment.yaml, deploy/example/statefulset.yaml, test/e2e/driver/blob_csi_driver.go, test/e2e/testsuites/testsuites.go
/kind bug
fix: set timeout(30s) for csi-provisioner
By default it's 15s which may cause timeout when create a new storage account and file share 
Fixes #
```
fix: set timeout(30s) for csi-provisioner
```
=> fix: set timeout(30s) for csi-provisioner

.github/workflows/ubuntu.yml, .travis.yml, Makefile, pkg/blob/fake_mount.go, pkg/blob/nodeserver_test.go, test/sanity/run-test.sh, test/sanity/run-tests-all-clouds.sh, vendor/k8s.io/utils/exec/testing/fake_exec.go, vendor/modules.txt
/kind test
test: add github action
Fixes #
```
none
```
=> test: add github action

charts/README.md, charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-controller.yaml, deploy/rbac-csi-blob-controller.yaml, hack/verify-helm-chart.sh
/kind bug
chore: remove csi-attacher since it's useless
Fixes #
```
none
```
=> chore: remove csi-attacher since it's useless

charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, deploy/csi-blob-controller.yaml, pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go, pkg/util/util.go, pkg/util/util_test.go
/kind bug
fix: add lock for prevent account list throttling
fix: set longer provision time to allow account creation
Fixes #
```
fix: add lock for prevent account list throttling
```
=> fix: add lock for prevent account list throttling

Makefile, deploy/example/deployment.yaml, deploy/example/nginx-pod-blob.yaml, deploy/example/statefulset.yaml, hack/verify-golint.sh, test/e2e/suite_test.go, test/utils/blob_log.sh
/kind test
test: switch to use mcr nginx image
Fixes #
```
test: switch to use mcr nginx image
```
=> test: switch to use mcr nginx image

README.md
/kind feature
chore: upgrade blobfuse version to 1.3.3
Fixes #
```
chore: upgrade blobfuse version to 1.3.3
```
=> chore: upgrade blobfuse version to 1.3.3

pkg/blob/blob.go, pkg/blob/controllerserver.go
/kind bug
fix: mount failure in bring key scenario
Fixes #
```
fix: mount failure in bring key scenario
```
=> fix: mount failure in bring key scenario

.github/workflows/static.yaml
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
Add `golangci-linter` to github actions
Fixes #
```
none
```
=> CI: Add `golangci-linter` to github actions

pkg/blob/controllerserver.go, test/e2e/dynamic_provisioning_test.go, test/e2e/suite_test.go, test/utils/get_storage_account_secret_name.sh
/kind test
test: add bring own key e2e test
Fixes #237
```
none
```
=> test: add bring own key e2e test

README.md
/kind feature
chore: upgrade to use blobfuse 1.3.4
Fixes #
```
feat: upgrade to use blobfuse 1.3.4
```
=> chore: upgrade to use blobfuse 1.3.4

charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, deploy/csi-blob-node.yaml
/kind bug
fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
"ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
Fixes #
```
fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
```
=> fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork

pkg/blob/nodeserver.go
/kind bug
fix: NFSv3 permission issue with non-root user, need to set `0777` for NFSv3 root folder in this PR.
There is different permission after mounting Blob NFSv3(`0755`) and Azure File NFSv4(`0777`)
```
total 9
drwxr-xr-x 2 root root    0 Oct  7 06:35 test
drwxrwxrwx 2 root root   64 Oct  7 03:48 test2
```
Fixes #
```
fix: NFSv3 permission issue with non-root user
```
=> fix: NFSv3 permission issue with non-root user

charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, deploy/csi-blob-node.yaml
/kind bug
fix: not schedule driver pod on virtual node
Fixes #
```
fix: not schedule driver pod on virtual node
```
=> fix: not schedule driver pod on virtual node

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go
/kind bug
fix: volumeid error in nfs pv
fixed PV/PVC usage does not work for NFS protocol
Fixes #262
```
fix: volumeid error in nfs pv
```
=> fix: volumeid error in nfs pv

deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml, deploy/example/pv-blobfuse-nfs.yaml, docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/blob_test.go
doc: refine PV parameters doc
Fixes #
```
doc: refine PV parameters doc
```
=> doc: refine PV parameters doc

deploy/example/statefulset-nonroot.yaml, pkg/blob/blob.go
/kind bug
fix: trim new line for azure storage account name
Fixes #
```
fix: trim new line for azure storage account name
```
=> fix: trim new line for azure storage account name

charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml, hack/verify-boilerplate.sh, hack/verify-golint.sh, hack/verify-gomod.sh, hack/verify-helm-chart.sh, pkg/blob/azure.go, pkg/blob/controllerserver.go
/kind feature
As Azure Stack and public Azure are using different storage account versions, we need to do some customizations for Azure Stack.
1. Azure Stack only supports Storage, so forcibly change the account kind to Storage (instead of StorageV2 or BlockBlobStorage).
2. Mount SSL certs.
3. Add an environment variable AZURE_ENVIRONMENT_FILEPATH, which is only used for Azure Stack: https://github.com/kubernetes-sigs/blob-csi-driver/blob/1ac16497e06b2b3601d2d0030b31e5450956e511/vendor/github.com/Azure/go-autorest/autorest/azure/environments.go#L220
This is not ideal, but the env variable must be passed before the ARM Client is created.
4. Make changes to the bash scripts under the `hack` folder so that `make verify` can …
=> chore: customization for Azure Stack Cloud

README.md, pkg/blob/controllerserver.go
/kind bug
Convert storageAccountType to Standard_LRS for Azure Stack as it only supports this account type.
Add limitations in README.
Fixes #
```
none
```
=> fix: only use Standard_LRS storageAccountType on Azure Stack

Makefile, hack/verify-boilerplate.sh, pkg/blobplugin/Dockerfile, test/e2e/README.md, test/e2e/pre_provisioning_test.go, test/e2e/suite_test.go, test/integration/README.md, test/integration/integration_test.go, test/sanity/README.md, test/sanity/run-test.sh, test/sanity/sanity_test.go, test/utils/credentials/credentials.go, test/utils/credentials/credentials_test.go
/kind test
Change the way credentials are loaded to make it work for Azure Stack test pipelines.
Modify docs accordingly.
Use -mod=vendor to build binaries.
Update blobfuse version for testing.
Fixes #
```
none
```
=> test: change the way credentials are loaded

deploy/example/nfs/README.md, deploy/example/nfs/statefulset.yaml, deploy/example/storageclass-blob-nfs.yaml
doc: fix NFS doc naming issue
Fixes #
```
doc: fix NFS doc naming issue
```
=> doc: fix NFS doc naming issue

charts/README.md, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-node.yaml
/kind bug
chore: upgrade node-driver-registrar version to v2.0.1
Fixes #
```
chore: upgrade node-driver-registrar version to v2.0.1
```
=> chore: upgrade node-driver-registrar version to v2.0.1

test/integration/run-tests-all-clouds.sh, test/sanity/run-tests-all-clouds.sh, test/sanity/sanity_test.go
Install the latest blobfuse binary for the Azure Stack test pipeline.
Fixes #
```
none
```
=> fix: install blobfuse binary for Azure Stack test pipeline

Makefile, test/e2e/README.md
/kind test
Use Helm 3.0 in e2e tests.
Fixes #
```
none
```
=> test: use helm 3 in e2e test

Makefile, charts/README.md, charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-controller.yaml
/kind feature
feat: support run controller on master node
Fixes #
```
feat: support run controller on master node
```
=> feat: support run controller on master node

go.mod, go.sum, pkg/blob/controllerserver.go, vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go, vendor/modules.txt
/kind feature
chore: upgrade to csi 1.3.0
Fixes #
```
chore: upgrade to csi 1.3.0
```
=> chore: upgrade to csi 1.3.0

charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/rbac-csi-blob-controller.yaml, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-controller.yaml, pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/util/util.go, test/e2e/driver/driver.go, test/e2e/dynamic_provisioning_test.go, test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go, test/integration/run-test.sh
/kind feature
This PR introduces support for volume resize by implementing the `ControllerVolumeExpand` RPC.
Fixes #78
N/A
```
none
```
=> feat: Add volume resize support

pkg/blob/blob.go, pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go, test/integration/run-test.sh
/kind feature
Implements node get stats endpoint in the node server
Fixes #292 
N/A
```
none
```
=> feat: Implement node get stats

Makefile, test/e2e/testsuites/testsuites.go
/kind bug
In tests, deploy pods/deployments only on Linux nodes.
For Azure Stack tests, we will spin up a separate buildx builder container with cert path mounted.
Fixes #
```
none
```
=> fix: only deploy test pods on Linux nodes

go.mod, test/sanity/run-test.sh, test/sanity/run-tests-all-clouds.sh, vendor/modules.txt
/kind test
test: refine sanity test script
Fixes #
```
none
```
=> test: refine sanity test script

test/sanity/run-test.sh, test/sanity/run-tests-all-clouds.sh
/kind test
test: upgrade sanity-test to v4.0.2
disabled node idemponent sanity test due to:
```
E1225 13:23:09.243995    8236 nodeserver.go:189] Mount failed with error: exit status 1, output: Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 404
[91m[1mSummarizing 1 Failure:[0m
[91m[1m[Fail] [0m[90mNode Service [0m[91m[1m[It] should be idempotent [0m
[37m/home/prow/go/src/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:140[0m
```
Fixes #
```
none
```
=> test: upgrade sanity-test to v4.0.2

pkg/blob/nodeserver.go
/kind bug
fix: use timestamp for tmp-path to v0.7
cherry-picked from https://github.com/kubernetes-sigs/blob-csi-driver/pull/229
Fixes #
```
fix: use timestamp for tmp-path to v0.7
```
=> fix: use timestamp for tmp-path to v0.7

pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go
/kind bug
should skip and return success if mount point is already mounted
Fixes #
```
fix: should skip and return success if mount point is already mounted
```
=> fix: should skip and return success if mount point is already mounted

README.md, charts/v0.7.1/blob-csi-driver/Chart.yaml, charts/v0.7.1/blob-csi-driver/templates/NOTES.txt, charts/v0.7.1/blob-csi-driver/templates/_helpers.tpl, charts/v0.7.1/blob-csi-driver/templates/csi-blob-controller.yaml, charts/v0.7.1/blob-csi-driver/templates/csi-blob-driver.yaml, charts/v0.7.1/blob-csi-driver/templates/csi-blob-node.yaml, charts/v0.7.1/blob-csi-driver/templates/rbac-csi-blob-controller.yaml, charts/v0.7.1/blob-csi-driver/templates/rbac-csi-blob-node.yaml, charts/v0.7.1/blob-csi-driver/templates/serviceaccount-csi-blob-controller.yaml, charts/v0.7.1/blob-csi-driver/templates/serviceaccount-csi-blob-node.yaml, charts/v0.7.1/blob-csi-driver/values.yaml, deploy/v0.7.1/csi-blob-controller.yaml, deploy/v0.7.1/csi-blob-driver.yaml, deploy/v0.7.1/csi-blob-node.yaml, deploy/v0.7.1/rbac-csi-blob-controller.yaml, deploy/v0.7.1/rbac-csi-blob-node.yaml, docs/install-csi-driver-v0.7.1.md
doc: add v0.7.1 deployment
Fixes #
```
doc: add v0.7.1 deployment
```
=> doc: add v0.7.1 deployment

.github/workflows/darwin.yaml, .github/workflows/ubuntu.yml, .github/workflows/windows.yaml
/kind test
test: enable GH actions on all branches
Fixes #
```
none
```
=> test: enable GH actions on all branches

charts/README.md
doc: update helm chart doc
Fixes #
```
none
```
=> doc: update helm chart doc

charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml
/kind bug
fix: ssl cert issue on non-debian agent node
Fixes #
cc @songjiaxun 
```
fix: ssl cert issue on non-debian agent node
```
=> fix: ssl cert issue on non-debian agent node

charts/README.md, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, charts/latest/blob-csi-driver/values.yaml
/kind feature
This PR adds the Kubelet path parameter in Helm chart installation.
Fixes #309 
none
```
feat: Add kubelet path parameter in helm chart installation
```
=> feat: Add kubelet path parameter in helm chart installation

pkg/blob/controllerserver.go
/kind bug
fix: account creation lock issue
`d.volLockMap.LockEntry(lockKey)` is only for account creation lock, original lock is too big, takes too much time in code.
Fixes #
```
fix: account creation lock issue
```
=> fix: account creation lock issue

Makefile, README.md, charts/README.md, charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml
/kind bug
Azure Stack needs certs to be mounted on the CSI containers.
Fixes #
```
none
```
=> fix: mount certs for Azure Stack

docs/csi-dev.md
Fix git clone directory path
```
none
```
=> chore: Fix git clone directory path

Makefile, hack/verify-examples.sh, test/e2e/suite_test.go
/kind test
test: refactor example verification test
Fixes #
```
none
```
=> test: refactor example verification test

Makefile
/kind bug
Fix CLOUD environment variable in Makefile.
Fixes #
```
none
```
=> fix: passing CLOUD correctly in Makefile for Azure Stack

test/e2e/dynamic_provisioning_test.go
/kind cleanup
Optimize test object creation.
Fixes #
```
none
```
=> fix: optimize test object creation

charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-controller.yaml, deploy/csi-blob-node.yaml
/kind feature
chore: upgrade livenessprobe to v2.2.0
Fixes #
```
none
```
=> chore: upgrade livenessprobe to v2.2.0

pkg/blob/controllerserver.go
/kind feature
Fixes #
```
feat: add lock in controller
```
=> feat: add lock in controller

pkg/blob/blob.go, pkg/blob/controllerserver.go
/kind feature
feat: add controller metrics
Fixes #
```
feat: add controller metrics
```
=> feat: add controller metrics

pkg/blob/azure.go, pkg/blob/azure_test.go, pkg/blob/blob.go, pkg/blob/nodeserver.go, pkg/blobplugin/main.go, test/sanity/run-test.sh
/kind feature
Ref: https://github.com/kubernetes-sigs/blob-csi-driver/issues/284
Remove the dependency of azure.json in node server.
For controller server, the azure.json is necessary. The file can be stored at the specified path or a kubernetes secrets.
For node server, the azure.json is unnecessary. If the file is not provided, need to provide the account key in volume attributions or a kubernetes secrets. Otherwise, the node has no permission to get and mount the blob container. 
Fixes #
```
feat: remove dependency of azure.json in node server
```
=> feat: remove dependency of azure.json in node server

pkg/blob/identityserver.go
/kind cleanup
cleanup: remove useless logs
Fixes #
```
none
```
=> cleanup: remove useless logs

deploy/example/e2e_usage.md
<docs>: bash is no longer installed in the nginx image changed demo to just run df -h directly
fix a doc issue
Fixes https://github.com/kubernetes-sigs/blob-csi-driver/edit/master/deploy/example/e2e_usage.md
Not a code change. Could change to just `sh` insted
```
none
```
=> Execute `df -h` command in the container for demo becuse bash is no longer installed in 

.github/workflows/darwin.yaml, .github/workflows/linux.yaml, .github/workflows/windows.yaml, hack/verify-helm-chart.sh
/kind test
test: add helm chart tgz file verification
Fixes #
```
none
```
=> test: add helm chart tgz file verification

hack/verify-helm-chart.sh
/kind test
test: add chart tgz files verification
Fixes #
```
none
```
=> test: add chart tgz files verification

pkg/blob/nodeserver.go
/kind bug
fix: use Environment.StorageEndpointSuffix if not specified
Fixes #
```
fix: use Environment.StorageEndpointSuffix if not specified
```
=> fix: use Environment.StorageEndpointSuffix if not specified

pkg/blob/azure.go
/kind bug
fix: add nil check for d.cloud on node
Fixes #
```
none
```
=> fix: always initialize driver cloud config

pkg/blob/azure_test.go, test/integration/run-test.sh
/kind test
test: add expand volume integration test
Fixes #
```
none
```
=> test: add expand volume integration test

charts/index.yaml, hack/verify-all.sh, hack/verify-helm-chart-files.sh, hack/verify-helm-chart.sh
/kind test
test: add verify-helm-chart-files.sh
Fixes #
```
none
```
=> test: add verify-helm-chart-files.sh

Makefile, pkg/csi-common/utils.go, pkg/csi-common/utils_test.go
/kind cleanup
chore: adjust log level for some CSI operations
Fixes #
```
none
```
=> chore: adjust log level for some CSI operations

test/utils/azure/azure_helper.go
/kind bug
Port this PR from Azure Disk CSI: https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/27c55d3450643bf4ed4f391c6c77820d51834a27
Use current value of resource group's managedBy property in tests.
Fixes #
```
none
```
=> fix: Use current value of resource group's managedBy property

Makefile, pkg/blob/nodeserver.go
/kind cleanup
chore: change authEnv setting
Fixes #
```
none
```
=> chore: change authEnv setting

.github/workflows/darwin.yaml, .github/workflows/linux.yaml, go.mod
/kind test
test: fix go mod issue with go1.16
Fixes #
```
none
```
=> test: fix go mod issue with go1.16

deploy/kustomization.yaml, hack/verify-yamllint.sh
/kind feature
This allows deployment with a kustomize process
Only add in the latest version (v1.0.0) and master.
Should it be more?
```
feat: add kustomize in deployment
```
=> feat: add kustomize in deployment

.gitignore, pkg/blobfuse-proxy/README.md, pkg/blobfuse-proxy/debpackage/DEBIAN/control, pkg/blobfuse-proxy/debpackage/etc/systemd/system/blobfuse-proxy.service
This PR creates a .deb package for blobfuse-proxy service
/kind feature
Fixes #
```
none
```
=> create a debian .deb package for blobfuse-proxy 

pkg/blob/controllerserver.go
/kind feature
fix: disable invalid storage class parameters
Fixes #
```
fix: disable invalid storage class parameters
```
=> fix: disable invalid storage class parameters

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: add more allowed storage class parameters
Fixes #
```
fix: add more allowed storage class parameters
```
=> fix: add more allowed storage class parameters

test/integration/run-test.sh
fix integration tests by manually un mounting the target path
Fixes #
```
none
```
=> fix integration tests by manually un mounting the target path

hack/install-protoc.sh
fix issues with hack/install-protoc.sh
/kind cleanup
Fixes #
```
none
```
=> fix issues with hack/install-protoc.sh

Makefile, pkg/blob/nodeserver.go, pkg/blobplugin/Dockerfile
/kind feature
chore: refactor Makefile
Fixes #
```
chore: refactor Makefile
```
=> chore: refactor Makefile

deploy/example/azure.json, pkg/blob/azure.go, pkg/blob/azure_test.go
/kind bug
fix: controller could run well without cloud provider
Fixes #
```
fix: controller could run well without cloud provider
```
=> fix: controller could run well without cloud provider

Makefile, test/external-e2e/run.sh, test/external-e2e/testdriver.yaml
Add external k8s e2e tests
/kind flake
Fixes #
```
none
```
=> Add external k8s e2e tests

README.md, deploy/blobfuse-proxy/blobfuse-proxy.yaml, deploy/example/storageclass-blobfuse-existing-container.yaml, deploy/example/storageclass-blobfuse-readonly.yaml, deploy/example/storageclass-blobfuse.yaml, pkg/blobplugin/Dockerfile, pkg/blobplugin/dev.Dockerfile, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: support blobfuse v1.3.7
Fixes #
```
feat: support blobfuse v1.3.7
```
=> feat: support blobfuse v1.3.7

deploy/blobfuse-proxy/blobfuse-proxy.yaml
/kind cleanup
chore: use mcr alpine image in blobfuse-proxy
Fixes #
```
none
```
=> chore: use mcr alpine image in blobfuse-proxy

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, test/e2e/pre_provisioning_test.go, test/e2e/testsuites/pre_provisioned_multiple_pods.go
…cified)
fix: add volume name as suffix in volumeID for static provisioning
This PR fixed the second pod mount error for static provisioning(containerName specified), this issue only exists from k8s 1.20
Fixes #
```
fix: second pod mount error for static provisioning(containerName specified)
```
=> fix: second pod mount error for static provisioning(containerName specified)

pkg/blobplugin/Dockerfile
/kind bug
chore: upgrade base image to fix CVE issue
Fixes #
```
chore: upgrade base image to fix CVE issue
```
=> chore: upgrade base image to fix CVE issue

Makefile
/kind cleanup
chore: fix image publish script
Fixes #
```
none
```
=> chore: fix image publish script

pkg/blob/controllerserver.go
/kind bug
fix: incorrect volumeid format
Fixes #
```
none
```
=> fix: incorrect volumeid format

deploy/example/storageclass-blob-nfs.yaml, pkg/blob/azure.go
/kind cleanup
chore: refine update svc endpoint lock
Fixes #
```
none
```
=> chore: refine update svc endpoint lock

pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go
/kind bug
fix: remove unnecessary lock in NodePublish
Fixes #
```
fix: remove unnecessary lock in NodePublish
```
=> fix: remove unnecessary lock in NodePublish

test/external-e2e/run.sh, test/external-e2e/testdriver.yaml
/kind test
test: run more external e2e tests
Fixes #
```
none
```
=> test: run more external e2e tests

test/external-e2e/run.sh
/kind test
test: run external test with 1.21 test suites
Fixes #
```
none
```
=> test: run external test with 1.20 test suites

deploy/example/storageclass-blobfuse.yaml, test/external-e2e/run.sh
/kind test
test: run external storage test with k8s 1.21 suites
Fixes #
```
none
```
=> test: run external storage test with k8s 1.21 suites

test/external-e2e/run.sh
/kind test
test: run external tests on NFS
Fixes #
```
none
```
=> test: run external tests on NFS

pkg/blob/blob.go
/kind bug
fix: sercretNamesapce empty issue in old driver PV
Fixes #
```
none
```
=> fix: sercretNamesapce empty issue in old driver PV

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go
/kind bug
fix: only read secret for inline volume
Fixes #
```
fix: only read secret for inline volume
```
=> fix: only read secret for inline volume

pkg/blob/azure.go, pkg/blob/azure_test.go
/kind cleanup
chore: add get key vault logs
Fixes #
```
none
```
=> chore: add get key vault logs

deploy/example/deployment-nfs.yaml, deploy/example/statefulset-nfs.yaml, deploy/example/statefulset-nonroot-nfs.yaml, hack/verify-examples.sh, test/external-e2e/run.sh
/kind test
test: add nonroot application tests 
Fixes #
```
none
```
=> test: add nonroot application tests 

pkg/blob/azure.go
/kind bug
fix: read cloud config from secret regression
Fixes #
```
fix: read cloud config from secret regression
```
=> fix: read cloud config from secret regression

deploy/example/e2e_usage.md, deploy/example/nginx-blobfuse-inline-volume.yaml, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pv-blobfuse-nfs.yaml, pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go, test/e2e/testsuites/testsuites.go
/kind feature
feat: add mountOptions for inline volume
Fixes #317
/hold
```
feat: add mountOptions for inline volume
```
=> feat: add mountOptions for inline volume

pkg/blob/blob.go, test/e2e/dynamic_provisioning_test.go
/kind test
fix: cannot read secret when mount blobfuse, current blobfuse mount all depends on read account key by cluster identity which is unexpected and low efficient.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_blob-csi-driver/460/pull-blob-csi-driver-e2e-vmss/1405459350775926784/build-log.txt
```
[pod/csi-blob-node-4ggxc/blob] I0617 10:00:42.360461       1 utils.go:114] GRPC call: /csi.v1.Node/NodeStageVolume
[pod/csi-blob-node-4ggxc/blob] I0617 10:00:42.360501       1 utils.go:115] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ff2b0a87-764a-440f-84f3-ff6550420883/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["-o …
```
=> fix: cannot read secret when mount blobfuse

pkg/blob/nodeserver.go
/kind bug
fix: blobfuse mount silent failure issue
In recent blobfuse version(v1.3.7 or prior release), blobfuse would return success even credentials are incorrect and then csi driver is actually writing data to local disk, that's a breaking change behavior. This PR also checks the output, to make sure if credentials are incorrect, it should fail.
related to blobfuse issue: https://github.com/Azure/azure-storage-fuse/issues/613
Fixes #450
```
fix: blobfuse mount silent failure issue
```
=> fix: blobfuse mount silent failure issue

pkg/blob/blob.go
/kind bug
fix: support msi auth type
Fixes #
```
fix: support msi auth type
```
=> fix: support msi auth type

docs/csi-debug.md, docs/csi-dev.md, docs/design.md, docs/install-csi-driver-v0.1.0.md, docs/install-csi-driver-v0.2.0.md, docs/install-csi-driver-v0.3.0.md, docs/install-csi-driver-v0.4.0.md, docs/install-driver-on-aks.md, test/e2e/testsuites/testsuites.go
/kind cleanup
I did a little rewording and also included a spelling correction in a test.
```
none
```
=> spelling corrections

pkg/blob/nodeserver.go
/kind bug
fix: conflict inline volume mount options with default
Fixes #
```
fix: conflict inline volume mount options with default
```
=> fix: conflict inline volume mount options with default

pkg/blob/nodeserver.go
/kind bug
fix: unmount failure due to incorrect mount path check
Fixes #474
```
fix: unmount failure due to incorrect mount path check
```
=> fix: unmount failure due to incorrect mount path check

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blobplugin/main.go, test/e2e/suite_test.go
/kind feature
chore: refine driver parameter setting
Fixes #
```
chore: refine driver parameter setting
```
=> chore: refine driver parameter setting

pkg/blob/azure.go, pkg/blob/azure_test.go, pkg/blob/blob.go, pkg/blob/version.go
/kind feature
feat: add driver userAgent in ARM request
- original userAgent: `Go/go1.14.2 (amd64-linux) go-autorest/v14.2.1; kubernetes-cloudprovider/v0.0.0-master+$Format:%h$`
- current userAgent: `blob.csi.azure.com/v1.5.0 gc/go1.16.6 (amd64-linux) db5fe240b5e8eebc52b1806bd33651f20ad41caf/2021-08-09T10:18:40Z`
Fixes #
```
feat: add driver userAgent in ARM request
```
=> feat: add driver userAgent in ARM request

pkg/blob/azure.go, pkg/blob/nodeserver.go
/kind bug
fix: storageEndpointSuffix issue in on-prem cluster
Fixes #493
```
fix: storageEndpointSuffix issue in on-prem cluster
```
=> fix: storageEndpointSuffix issue in on-prem cluster

pkg/blob/version.go, pkg/blob/version_test.go
/kind cleanup
chore: remove commit id & build date in userAgent
Fixes #
```
chore: remove commit id & build date in userAgent
```
=> chore: remove commit id & build date in userAgent

test/manifest/linux-vmss.json, test/manifest/linux.json
/kind test
test: remove deprecated ccm config
Fixes #
```
none
```
=> test: remove deprecated ccm config

deploy/blobfuse-proxy/blobfuse-proxy.yaml
/kind cleanup
cleanup: remove deb file after proxy installed
Fixes #
```
none
```
=> cleanup: remove deb file after proxy installed

README.md, charts/README.md, deploy/blobfuse-proxy/README.md, deploy/csi-blob-node.yaml, pkg/blobfuse-proxy/README.md
doc: update blobfuse-proxy doc
Fixes #
```
none
```
=> doc: update blobfuse-proxy doc

Makefile, pkg/blobplugin/Dockerfile
/kind feature
chore: upgrade base image to bulleye
Fixes #
```
chore: upgrade base image to bulleye
```
=> chore: upgrade base image to bulleye

deploy/blobfuse-proxy/blobfuse-proxy.yaml
/kind feature
feat: download binaries from initContainer in blobfuse-proxy
Fixes #
/hold
```
feat: download binaries from initContainer in blobfuse-proxy
```
=> feat: download binaries from initContainer in blobfuse-proxy

deploy/blobfuse-proxy/blobfuse-proxy.yaml
/kind feature
feat: disable download in blobfuse-proxy deployment
Fixes #
```
feat: disable download in blobfuse-proxy deployment
```
=> feat: disable download in blobfuse-proxy deployment

deploy/blobfuse-proxy/blobfuse-proxy.yaml
/kind bug
fix: change blobfuse install script
Fixes #522
```
fix: change blobfuse install script
```
=> fix: change blobfuse install script

charts/index.yaml
/kind bug
Fixes #569
```
none
```
=> fix: v1.6.0 chart index

deploy/example/remove-mlocate-ds.yaml
doc: add remove-mlocate daemonset
Fixes #
```
none
```
=> doc: add remove-mlocate daemonset

pkg/csi-common/controllerserver-default.go, pkg/csi-common/controllerserver-default_test.go, pkg/csi-common/nodeserver-default.go, pkg/csi-common/nodeserver-default_test.go
/kind cleanup
1. Improve csicommon package to align with csi spec v1.5
2. Fix some typos 
Fixes #
```
none
```
```
none
```
=> chore: update csicommon to csi spec v1.5

pkg/blobplugin/Dockerfile
/kind cleanup
chore: remove nfs-kernel-server package
Fixes #214
```
none
```
=> chore: remove nfs-kernel-server package

.github/workflows/windows.yaml
/kind cleanup
Enable build test in windows GitHub action
Fixes #
none
```
none
```
=> chore: enable build test in windows GitHub action

.github/workflows/pluto.yaml
/kind test
test: add apiVersion verification test
Fixes #
```
none
```
=> test: add apiVersion verification test

.github/workflows/pluto.yaml, pkg/blobplugin/Dockerfile
/kind bug
fix: CVE-2021-43618 in Ubuntu image
Fixes #
```
test/azuredisk-csi:latest (debian 11.0)
=======================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |     FIXED VERSION      |                 TITLE                 |
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| libgmp10 | CVE-2021-43618   | HIGH     | …
```
=> fix: CVE-2021-43618 in Ubuntu image

go.mod, go.sum, vendor/golang.org/x/text/internal/language/language.go, vendor/golang.org/x/text/internal/language/parse.go, vendor/golang.org/x/text/language/parse.go, vendor/modules.txt
/kind bug
fix: CVE-2021-38561 with golang lib
```
==========================
Total: 1 (UNKNOWN: 1, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
+-------------------+------------------+----------+-------------------+---------------+---------------------------------------+
|      LIBRARY      | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+-------------------+------------------+----------+-------------------+---------------+---------------------------------------+
| golang.org/x/text | CVE-2021-38561   | UNKNOWN  | v0.3.6            | 0.3.7         | -->avd.aquasec.com/nvd/cve-2021-38561 |
+-------------------+------------------+----------+-------------------+-------- …
```
=> fix: CVE-2021-38561 with golang lib

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/controllerserver.go, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: add secretName in storage class parameters
Fixes #
```
feat: add secretName in storage class parameters
```
=> feat: add secretName in storage class parameters

Makefile, pkg/blobplugin/Dockerfile, test/integration/run-test.sh, test/sanity/run-test.sh
/kind feature
feat: support arm64
Fixes #
```
feat: support arm64
```
=> feat: support arm64

pkg/blobplugin/Dockerfile
/kind cleanup
chore: refactor Dockerfile
Fixes #
```
FailedMount: MountVolume.MountDevice failed for volume "pvc-a44b6488-f47e-406f-a25b-781adb716759" : rpc error: code = Unknown desc = Mount failed with error: exit status 127, output: blobfuse: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```
```
none
```
=> chore: refactor Dockerfile

pkg/blob/controllerserver.go
/kind bug
Fix the Confirmed field of ValidateVolumeCapabilities response to let it actually supports all capabilities.
Fixes #
```
none
```
=> fix the Confirmed field of ValidateVolumeCapabilities response

test/sanity/run-test.sh
test: add one sanity test
Fixes #
```
none
```
=> test: add one sanity test

.github/workflows/static.yaml, pkg/blob/azure.go, pkg/blob/azure_test.go, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go, pkg/blobfuse-proxy/server/server.go, pkg/blobplugin/main.go, test/e2e/testsuites/testsuites.go, test/utils/azure/azure_helper.go, test/utils/credentials/credentials.go
/kind test
test: add more golinters
Fixes #
```
none
```
=> test: add more golinters

pkg/blobplugin/Dockerfile
/kind bug
fix: CVE-2021-3996 in image build
Fixes #
```
fix: CVE-2021-3996 in image build
```
=> fix: CVE-2021-3996 in image build

pkg/blob/blob.go
/kind bug
fix: remove special chars when parsing account name from secret
The space char could be:
```
'\t', '\n', '\v', '\f', '\r', ' ', 0x85, 0xA0
```
Fixes #
```
fix: remove space when parsing account name from secret
```
=> fix: remove special chars when parsing account name from secret

.github/workflows/codespell.yml, .github/workflows/shellcheck.yaml, README.md, pkg/blob/blob.go, pkg/blob/nodeserver.go, pkg/util/util.go, test/integration/run-test.sh, test/sanity/run-tests-all-clouds.sh, test/utils/blob_log.sh, test/utils/check_driver_pods_restart.sh, test/utils/get_storage_account_secret_name.sh
/kind test
test: add codespell shellcheck github actions
Fixes #
```
none
```
=> test: add codespell shellcheck github actions

charts/README.md, deploy/example/storageclass-blob-nfs.yaml, deploy/example/storageclass-blob-secret.yaml, deploy/example/storageclass-blobfuse-existing-container.yaml, deploy/example/storageclass-blobfuse-readonly.yaml, deploy/example/storageclass-blobfuse.yaml, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go
/kind bug
fix: delete volume failure when account is deleted
<details>
I0218 03:56:38.040196       1 utils.go:114] GRPC call: /csi.v1.Controller/DeleteVolume
I0218 03:56:38.040328       1 utils.go:115] GRPC request: {"volume_id":"mc_andy-aks122_andy-aks122_eastus2#fusede8aeb3428474160906#pvc-78dad8de-2863-4615-b4c4-96ff8075b91b"}
I0218 03:56:38.082190       1 azure_storageaccountclient.go:193] Received error in storageaccount.listkeys.request: resourceID: /subscriptions/xxx/resourceGroups/mc_andy-aks122_andy-aks122_eastus2/providers/Microsoft.Storage/storageAccounts/xxx, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource …
=> fix: delete volume failure when account is deleted

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: add mountPermissions parameter in storage class
user could set customized mountPermissions in storage class, e.g.
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: blob-nfs
provisioner: blob.csi.azure.com
parameters:
protocol: nfs
mountPermissions: "0755"
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
Fixes #
```
feat: add mountPermissions parameter in storage class
```
=> feat: add mountPermissions parameter in storage class

Makefile
/kind test
test: remove runOnMaster config in e2e test
Fixes #
```
none
```
=> test: remove runOnMaster config in e2e test

pkg/blobplugin/Dockerfile
/kind cleanup
cleanup: unnecessary deb file in Dockerfile
Fixes #
```
none
```
=> cleanup: unnecessary deb file in Dockerfile

pkg/blobplugin/Dockerfile
/kind bug
fix: CVE-2022-0778 in image build
Fixes #
```
fix: CVE-2022-0778 in image build
```
=> fix: CVE-2022-0778 in image build

deploy/example/pv-blobfuse-nfs.yaml, deploy/example/storageclass-blob-nfs.yaml, test/e2e/dynamic_provisioning_test.go
doc: add nconnect mount option in nfs example
Fixes #
```
none
```
=> doc: add nconnect mount option in nfs example

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/controllerserver.go
/kind bug
fix: default secretNamespace should be pvc namespace, original secret namespace setting may have random selection issue.
Fixes #
```
fix: default secretNamespace should be pvc namespace
```
=> fix: default secretNamespace should be pvc namespace

pkg/blobplugin/Dockerfile
/kind bug
fix: CVE-2018-25032 in image build
Fixes #
```
fix: CVE-2018-25032 in image build
```
=> fix: CVE-2018-25032 in image build

deploy/example/deployment-nfs.yaml, deploy/example/deployment.yaml, deploy/example/nfs/README.md, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pv-blobfuse-nfs.yaml, deploy/example/pvc-blob-csi-static.yaml, deploy/example/storageclass-blob-nfs.yaml
doc: refine static PV docs
Fixes #
```
none
```
=> doc: refine static PV docs

pkg/blob/blob.go, pkg/blob/controllerserver.go
/kind bug
fix: default namespace issue
default namespace should be set if secretNamespace is empty
Fixes #
```
fix: default namespace issue
```
=> fix: default namespace issue

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, test/integration/run-test.sh
/kind bug
fix: should return error for block volumeMode
Fixes #
```
fix: should return error for block volumeMode
```
=> fix: should return error for block volumeMode

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind cleanup
chore: refine VolumeCapabilities check
Fixes #
```
none
```
=> chore: refine VolumeCapabilities check

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: add containerNamePrefix in storage class
Fixes #
```
feat: add containerNamePrefix in storage class
```
=> feat: add containerNamePrefix in storage class

deploy/example/deployment.yaml, deploy/example/e2e_usage.md, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pvc-blob-csi-static.yaml, deploy/example/pvc-blob-csi.yaml, deploy/example/statefulset-nonroot.yaml, deploy/example/statefulset.yaml, deploy/example/storageclass-blob-secret.yaml, deploy/example/storageclass-blobfuse-existing-container.yaml, deploy/example/storageclass-blobfuse-readonly.yaml, deploy/example/storageclass-blobfuse.yaml
doc: rename storage class name from blob to blob-fuse
Fixes #
```
doc: rename storage class name from blob to blob-fuse
```
=> doc: rename storage class name from blob to blob-fuse

test/e2e/suite_test.go, test/utils/azure/azure_helper.go
/kind test
test: add account creation leak test
This test would check whether there are account creation leak issue in e2e test.
Fixes #
```
none
```
=> test: add account creation leak test

pkg/blobplugin/Dockerfile
/kind bug
fix: CVE-2022-1271 in image build
```
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| gzip     | CVE-2022-1271    | HIGH     | 1.10-4            | 1.10-4+deb11u1    | gzip: arbitrary-file-write           |
|          |                  |          |                   |                   | vulnerability                        |
|          |                  |          |                   | …
```
=> fix: CVE-2022-1271 in image build

pkg/blobplugin/Dockerfile
/kind cleanup
chore: refine package patching in image build
Fixes #
```
none
```
=> chore: refine package patching in image build

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go, pkg/blobplugin/Dockerfile
/kind cleanup
chore: refine metrics naming
Fixes #
<details>
```
"Observed Request Latency" latency_seconds=0.105987659 request="blob_csi_driver_controller_create_volume" resource_group="kubetest-lgtohtmh" subscription_id="0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e" source="blob.csi.azure.com" volumeid="kubetest-lgtohtmh#fuse4ecb36296b9441d4abf#pvc-96774081-3a68-4a46-924b-e4297d82c67c" result_code="succeeded"
"Observed Request Latency" latency_seconds=0.010556104 request="blob_csi_driver_controller_delete_volume" resource_group="kubetest-lgtohtmh" subscription_id="0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e" source="blob.csi.azure.com" …
```
=> chore: refine metrics naming

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
/kind feature
chore: append secretNamespace to volumeid
Fixes #
```
none
```
=> chore: append secretNamespace to volumeid

pkg/blob/blob.go
/kind cleanup
chore: add one logging for account hit in secret 
Fixes #
```
none
```
=> chore: add one logging for account hit in secret 

docs/driver-parameters.md, pkg/blob/nodeserver.go, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: skip chmod if mountPermissions is 0 after mount
Fixes #
**Does this PR introduce a user-facing change?**:
```release-note
feat: skip chmod if mountPermissions is 0 after mount
```
=> feat: skip chmod if mountPermissions is 0 after mount

pkg/blob/blob.go
/kind cleanup
chore: add cloud config logging in driver init
Fixes #
```
none
```
=> chore: add cloud config logging in driver init

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/nodeserver.go
/kind bug
fix: bypass chmod if mounting point permissions are correct
Fixes #
```
none
```
=> fix: bypass chmod if mounting point permissions are correct

pkg/blob/azure.go
/kind cleanup
chore: set as info log if cloud-provider-azure secret not found
Fixes #
```
none
```
=> chore: set as info log if cloud-provider-azure secret not found

pkg/blob/azure.go
/kind bug
fix: respect DisableAzureStackCloud on AKS control plane setting
Fixes #
```
fix: respect DisableAzureStackCloud on AKS control plane setting
```
=> fix: respect DisableAzureStackCloud on AKS control plane setting

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: support pv/pvc metadata for containerName parameter
Fixes #
```
feat: support pv/pvc metadata for containerName parameter
```
=> feat: support pv/pvc metadata for containerName parameter

pkg/blob/version.go, pkg/blob/version_test.go
chore: shorten userAgent
`Go/go1.17 (amd64-linux) go-autorest/v14.2.1 blob.csi.azure.com/v1.12.0 gc/go1.17 (amd64-linux) OSS-helm` --> 
`Go/go1.17 (amd64-linux) go-autorest/v14.2.1 blob.csi.azure.com/v1.12.0 OSS-helm`
Fixes #
```
none
```
=> chore: shorten userAgent

charts/index.yaml
doc: update chart index
Fixes #
```
none
```
=> doc: update chart index

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go
/kind bug
fix: CSI function should return internal error
Fixes #
```
fix: CSI function should return internal error
```
=> fix: CSI function should return internal error

docs/read-from-secret.md
Typos `Namesapce` is changed into `Namespace`
```
none
```
=> Fixed typos in read-from-secret.md file

.github/workflows/codespell.yml, pkg/blob/blob_test.go
/kind cleanup
fix: fixing codespell errors
Fixes #
```
none
```
=> fix: fixing codespell errors

deploy/example/nfs/README.md, deploy/example/pv-blobfuse-nfs.yaml, deploy/example/storageclass-blob-nfs.yaml
doc: remove nconnect mount option, `nconnect=8` mount option would lead to blob nfs list directory failure
Fixes #
```
none
```
=> doc: remove nconnect mount option

test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go, test/utils/azure/keyvault_helper.go
=> add e2e test for resourceID

CONTRIBUTING.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #756
=> Resolved issue of broken link

hack/verify-all.sh, hack/verify-helm-chart-index.sh
/feature
add test for helm repo install
Fixes #750
use `sh ./test/utils/check_helm_repo.sh` in dir to check url in index.yaml
```
none
```
=> feat: add helm repo install check

pkg/blobplugin/Dockerfile
/kind feature
chore: upgrade base image debian-base:bullseye-v1.4.2
Fixes #
```
none
```
=> chore: upgrade base image debian-base:bullseye-v1.4.2

pkg/blobfuse-proxy/init.sh
/kind bug
should remove the bobfuse-proxy binary file before `cp` to it, otherwise error `cp: cannot create regular file '/usr/bin/blobfuse-proxy': Text file busy` occured.
Fixes #
```
none
```
=> fix: rm blobfuse-proxy before cp to avoid Text file busy error

pkg/blob/azure.go, pkg/blob/azure_test.go
/kind bug
fix: increase api qps for blob kubeclient
- original default values
```
--kube-api-qps <num>: The number of requests per second sent by a Kubernetes client to the Kubernetes API server. Defaults to 5.0.
--kube-api-burst <num>: The number of requests to the Kubernetes API server, exceeding the QPS, that can be sent at any given time. Defaults to 10.
```
Fixes #
```
fix: increase api qps for blob kubeclient
```
=> fix: increase api qps for blob kubeclient

pkg/blob/azure.go, pkg/blob/azure_test.go, pkg/blob/blob.go, pkg/blobplugin/main.go
/kind feature
feat: make kube-api-qps configurable
Fixes #
```
feat: make kube-api-qps configurable
```
=> feat: make kube-api-qps configurable

pkg/blobfuse-proxy/init.sh, pkg/blobfuse-proxy/server/server.go
when `init.sh` running `dpkg -i /etc/packages-microsoft-prod.deb`,  need to enter `y` to continue 
The solution refers to https://stackoverflow.com/questions/45349571/how-to-install-deb-with-dpkg-non-interactively
Fixes #
```
none
```
=> fix: make sure blobfuse2 is installed when init blobfuse node driver

test/e2e/dynamic_provisioning_test.go
/kind test
test: refine blobfuse2 e2e test
This PR added a blobfuse2 specific mount options in e2e test, that could ensure the blobfuse2 test is correct even it's using blobfuse v1 mount actually.
Fixes #
```
none
```
=> test: refine blobfuse2 e2e test

test/manifest/linux-vmss.json
=> chore: fix e2e: disable-admission-plugins: PodSecurity

test/manifest/linux.json
=> fix e2e: disable podSecurity

go.mod, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, test/e2e/testsuites/testsuites.go, test/utils/azure/authorization_helper.go
/kind cleanup
Use k8s utils pointer instead of Azure autorest/to
- to.FooPtr becomes pointer.Foo
- to.Foo becomes pointer.FooDeref with an appropriate default
- to.StringSlicePtr becomes &
This is related to https://github.com/kubernetes/kubernetes/issues/112431 (but doesn’t fix it).
```
none
```
=> cleanup: Use k8s utils pointer instead of Azure autorest/to

deploy/example/e2e_usage.md, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pv-blobfuse-nfs.yaml, deploy/example/storageclass-blobfuse2.yaml, docs/driver-parameters.md, test/external-e2e/run.sh
/kind test
test: run external test on blobfuse2
Fixes #
```
none
```
=> test: add blobfuse2 external tests 

test/e2e/dynamic_provisioning_test.go, test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go, test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go, test/e2e/testsuites/dynamically_provisioned_volume_unmount_tester.go, test/e2e/testsuites/specs.go
=> add e2e test for unmount deleted volume

pkg/blobplugin/Dockerfile
/kind cleanup
Update the debian base image to the latest release.
None
None
**Does this PR introduce a user-facing change?**:
```release-note
None
```
=> Update debian-base image to v1.4.3

pkg/blobfuse-proxy/server/server.go
Fixes https://github.com/Azure/azure-storage-fuse/issues/1015
```
none
```
=> fix: mount failed on ubuntu 22.04(aks 1.25.2)

Makefile, hack/boilerplate/boilerplate.py, pkg/blobfuse-proxy/server/server.go, test/external-e2e/run.sh
/kind bug
[release-1.19] fix: mount failed on ubuntu 22.04(aks 1.25.2)
cherry-pick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/827
Fixes #
```
[release-1.19] fix: mount failed on ubuntu 22.04(aks 1.25.2)
```
=> [release-1.19] fix: mount failed on ubuntu 22.04(aks 1.25.2)

Makefile
test: fix capz test failure
This PR uses a different image tag env to avoid conflict with CCM build in capz
Fixes #
test: fix capz test failure
```
none
```
=> test: fix capz test failure

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go
/kind cleanup
cleanup: remove context.TODO
Fixes #
```
none
```
=> cleanup: remove context.TODO

hack/verify-examples.sh, pkg/blob/blob.go, pkg/blob/blob_test.go
/kind bug
fix: support getting sasToken, msiSecret, SPN from secret
fix ported from https://github.com/kubernetes-sigs/blob-csi-driver/pull/867
Fixes #
```
fix: support getting sasToken, msiSecret, SPN from secret
```
=> [release-1.20] fix: support getting sasToken, msiSecret, SPN from secret

deploy/example/nfs/statefulset.yaml, deploy/example/statefulset-nfs.yaml, deploy/example/statefulset-nonroot-nfs.yaml, deploy/example/statefulset-nonroot.yaml, deploy/example/statefulset.yaml
/kind cleanup
The volume.beta.kubernetes.io/storage-class annotation is deprecated since v1.9.
Changed it to a new way to deal with some e2e issues.
Fixes #
```
none
```
=> test(e2e): change the storageclass configuration method in the test file

pkg/blob/nodeserver.go
/kind bug
fix: increase mount timeout check as 60s
the blobfuse2 mount sometimes costs 18s to mount complete, this PR increases the mount timeout as 60s to fix mount timeout issue: https://github.com/Azure/azure-storage-fuse/issues/1079#issuecomment-1510960419
Fixes #
```
fix: increase mount timeout check as 60s
```
=> fix: increase mount timeout check as 60s

pkg/blob/azure_test.go, pkg/blob/blob_test.go, pkg/blob/nodeserver.go, test/utils/credentials/credentials.go, test/utils/credentials/credentials_test.go
/kind cleanup
Replace the deprecated ioutil method, Because they are no longer recommended in go version 1.16 or 1.17
Fixes #
```
none
```
=> cleanup: replace deprecated ioutil method

pkg/blob/nodeserver.go, pkg/blobfuse-proxy/server/server.go, pkg/util/util.go, pkg/util/util_test.go
=> fix: mount failure when mountOptions is empty

pkg/blob/nodeserver.go, pkg/blobfuse-proxy/server/server.go, pkg/util/util.go, pkg/util/util_test.go
/kind bug
cherry pick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/893
Fixes #
```
fix: mount failure when mountOptions is empty
```
=> [release-1.20] fix: mount failure when mountOptions is empty

hack/verify-examples.sh
/kind test
test: run nonroot pod test on blobfuse2 mount
Fixes #
```
none
```
=> test: run nonroot pod test on blobfuse2 mount

pkg/blob/blob.go
/kind bug
There are 4 auth types: `Key, SAS, MSI, SPN`, and secret is only optional for `MSI` auth, this PR fixes the secret not found issue when secret is not provided for MSI auth, this bug was introduced by https://github.com/kubernetes-sigs/blob-csi-driver/pull/867
Fixes #926
```
none
```
=> fix: msi auth issue when secret is not provided

.github/dependabot.yaml
/kind test
build: add dependabot job for dockerfile updates
Fixes #
```
none
```
=> build: add dependabot job for dockerfile updates

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/blob_test.go
/kind feature
feat: support setting AzureStorageSPNClientID/TenantId in secret
Fixes #941
```
feat: support setting AzureStorageSPNClientID/TenantId in secret
```
=> feat: support setting AzureStorageSPNClientID/TenantId in secret

deploy/uninstall-driver.sh
=> chore: fix uninstall-driver to make it backward compatibility

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: dynamic provisioning support with blobfuse msi auth
Fixes #
```
fix: dynamic provisioning support with blobfuse msi auth
```
=> fix: dynamic provisioning support with blobfuse msi auth

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: dynamic provisioning support with blobfuse msi auth
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/954
Fixes #
```
fix: dynamic provisioning support with blobfuse msi auth
```
=> [release-1.22] fix: dynamic provisioning support with blobfuse msi auth

pkg/blob/blob.go, pkg/blob/blob_test.go
/kind cleanup
cleanup: remove secret print in error message
Fixes #
```
none
```
=> cleanup: remove secret print in error message

Makefile, charts/README.md, charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, charts/latest/blob-csi-driver/values.yaml, pkg/blob/blob.go, pkg/blob/nodeserver.go, pkg/blobfuse-proxy/init.sh, pkg/blobplugin/Dockerfile, pkg/blobplugin/main.go, test/external-e2e/run.sh
This is an cherry-pick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/987
=> [release 1.22] feat: support aznfs mount helper

deploy/example/e2e_usage.md, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pv-blobfuse-nfs.yaml, docs/driver-parameters.md
doc: update volumeHandle doc
Fixes #
```
none
```
=> doc: update volumeHandle doc

pkg/blobplugin/main.go
/kind cleanup
Fixes #
```
none
```
=> chore: set enable-aznfs-mount default value as false

pkg/blob/controllerserver.go
/kind cleanup
fix: refine create volume metrics
Fixes #
```
fix: refine create volume metrics
```
=> fix: refine create volume metrics

test/e2e/driver/blob_csi_driver.go
cleanup: fix typo
Fixes #
```
none
```
=> cleanup: fix typo

Makefile, test/external-e2e/run.sh
test: remove override in blobfuse proxy enabled test
Fixes #
```
none
```
=> test: remove override in blobfuse proxy enabled test

Makefile, test/utils/blob_log.sh
test: don't return error in blob_log.sh
Fixes #
```
none
```
=> test: don't return error in blob_log.sh

pkg/blobfuse-proxy/init.sh
/kind bug
fix: support arm in init.sh
Fixes #
```
none
```
=> fix: support arm in init.sh

deploy/example/storageclass-blobfuse.yaml, deploy/example/storageclass-blobfuse2.yaml, docs/driver-parameters.md
doc: add ZRS storage sku in the doc
Fixes #
```
none
```
=> doc: add ZRS storage sku in the doc

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go
/kind bug
Fixes #1084
```
none
```
=> fix: make aznfs protocol consistent with nfs

charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, charts/latest/blob-csi-driver/values.yaml, deploy/csi-blob-node.yaml, pkg/blobfuse-proxy/init.sh, pkg/blobfuse-proxy/install-proxy-mariner.sh, pkg/blobfuse-proxy/install-proxy-rhcos.sh, pkg/blobfuse-proxy/install-proxy-ubuntu.sh, pkg/blobfuse-proxy/server/server.go, pkg/blobplugin/Dockerfile, pkg/util/util.go, pkg/util/util_test.go
This is a cherry-pick of #1045
=> [release-1.23] feat: support blobfuse-proxy on OpenShift

pkg/blobplugin/Dockerfile
This is a cherry-pick of #1090
=> [release-1.21] feat: switch to bookworm debian base image

pkg/blobplugin/Dockerfile
This is a cherry-pick of #1090
=> [release-1.22] feat: switch to bookworm debian base image

pkg/blobplugin/Dockerfile
This is a cherry-pick of #1090
=> [release-1.23] feat: switch to bookworm debian base image

.github/workflows/static.yaml, .golangci.yml, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/fake_mount.go, pkg/blob/identityserver.go, pkg/blob/nodeserver.go, pkg/blobfuse-proxy/server/server.go, pkg/blobplugin/main.go, pkg/csi-common/driver_test.go, pkg/csi-common/server_test.go, pkg/util/util.go, pkg/util/util_test.go, test/e2e/driver/blob_csi_driver.go, test/e2e/testsuites/dynamically_provisioned_inline_volume.go, test/e2e/testsuites/specs.go
/kind test
test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```
=> test: upgrade golangci/golangci-lint-action to v1.54

deploy/example/nfs/README.md, deploy/example/pv-blobfuse-nfs.yaml, deploy/example/storageclass-blob-nfs.yaml
doc: add nconnect mount option in the doc
Fixes #
```
none
```
=> doc: add nconnect mount option in the doc

deploy/example/e2e_usage.md, deploy/example/nginx-blobfuse-inline-volume.yaml, deploy/example/nginx-pod-blob.yaml, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pv-blobfuse-nfs.yaml, deploy/example/statefulset-nfs.yaml, deploy/example/statefulset-nonroot-nfs.yaml, deploy/example/statefulset-nonroot.yaml, deploy/example/statefulset.yaml
doc: fix readOnly setting doc
- following csi.readOnly is not supported in CSI driver
```
csi:
driver: blob.csi.azure.com
readOnly: false
```
Fixes #
```
none
```
=> doc: fix readOnly setting doc

go.mod, go.sum, pkg/blobfuse-proxy/main.go, vendor/github.com/go-logr/logr/slogr/sloghandler.go, vendor/github.com/go-logr/logr/slogr/slogr.go, vendor/github.com/go-logr/logr/slogr/slogsink.go, vendor/k8s.io/klog/v2/.golangci.yaml, vendor/k8s.io/klog/v2/internal/buffer/buffer.go, vendor/k8s.io/klog/v2/internal/clock/clock.go, vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go, vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go, vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go, vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go, vendor/k8s.io/klog/v2/k8s_references_slog.go, vendor/k8s.io/klog/v2/klog.go, vendor/k8s.io/klog/v2/klog_file.go, vendor/k8s.io/klog/v2/klogr.go, vendor/k8s.io/klog/v2/klogr_slog.go, vendor/modules.txt
/kind cleanup
Bumps [k8s.io/klog/v2](https://github.com/kubernetes/klog) from 2.100.1 to 2.110.1.
bumps #1142 issue by manual
Fixes #
```
none
```
=> chore(deps): bump k8s.io/klog/v2 from 2.100.1 to 2.110.1

deploy/v1.22.4/csi-blob-node.yaml, deploy/v1.23.2/csi-blob-node.yaml
/kind cleanup
https://github.com/kubernetes-sigs/blob-csi-driver/pull/1151
Fixes #
```
chore: support deploy aznfs mount helper in v1.22 and v1.23
```
=> chore: support deploy aznfs mount helper in v1.22 and v1.23

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
Fix: fix storage identity typo issue
Fixes #
```
none
```
=> doc: fix storage identity typo

test/external-e2e/testdriver-blobfuse.yaml, test/external-e2e/testdriver-nfs.yaml
/kind test
test: add more external e2e tests
Fixes #
```
none
```
=> test: add more external e2e tests

pkg/blobplugin/Dockerfile
/kind feature
feat: upgrade to aznfs 2.0.1 version for nfs mount
Fixes #
```
feat: upgrade to aznfs 2.0.1 version for nfs mount
```
=> feat: upgrade to aznfs 2.0.1 version for nfs mount

.github/workflows/static.yaml, .golangci.yml, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/fake_mount.go, pkg/blob/identityserver.go, pkg/blob/nodeserver.go, pkg/blobfuse-proxy/server/server.go, pkg/blobplugin/main.go, pkg/csi-common/driver_test.go, pkg/csi-common/server_test.go, pkg/util/util_test.go, test/e2e/driver/blob_csi_driver.go, test/e2e/testsuites/dynamically_provisioned_inline_volume.go, test/e2e/testsuites/specs.go, test/utils/azure/azure_helper.go
/kind test
This is a cherry-pick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1119
Fixes #
```
none
```
=> [release-1.22] test: upgrade golangci/golangci-lint-action to v1.54

deploy/example/cloning/README.md
doc: fix volume cloning doc
Fixes #
```
none
```
=> doc: fix volume cloning doc

.github/workflows/static.yaml, .golangci.yml, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/fake_mount.go, pkg/blob/identityserver.go, pkg/blob/nodeserver.go, pkg/blobfuse-proxy/server/server.go, pkg/blobplugin/main.go, pkg/csi-common/driver_test.go, pkg/csi-common/server_test.go, pkg/util/util_test.go, test/e2e/driver/blob_csi_driver.go, test/e2e/testsuites/dynamically_provisioned_inline_volume.go, test/e2e/testsuites/specs.go, test/utils/azure/azure_helper.go
/kind test
This is a cherry-pick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1119
Fixes #
```
none
```
=> [release-1.21] test: upgrade golangci/golangci-lint-action to v1.54

test/sanity/run-test.sh
/kind test
test: always use latest azcopy version in sanity test
Fixes #
```
none
```
=> test: always use latest azcopy version in sanity test

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/nodeserver.go
/kind bug
fix: mountPermission settting issue due to case insensitive parameter
Fixes #
```
fix: mountPermission settting issue due to case insensitive parameter
```
=> fix: mountPermission settting issue due to case insensitive parameter

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind feature
fix: add cache in sastoken fallback
Fixes #
```
none
```
=> cleanup: add cache in sastoken fallback

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go, pkg/blob/nodeserver_test.go, pkg/util/util.go, pkg/util/util_test.go, test/e2e/dynamic_provisioning_test.go, test/external-e2e/run.sh, test/external-e2e/testdriver-blobfuse.yaml, test/external-e2e/testdriver-nfs.yaml
/kind feature
feat: support volume mount group and add FSGroupChangePolicy param for NFS mount
Fixes #
```
feat: support volume mount group and add FSGroupChangePolicy param for NFS mount
```
=> feat: support volume mount group and add FSGroupChangePolicy param for NFS mount

pkg/blobplugin/Dockerfile
/kind feature
feat: upgrade to aznfs 2.0.3 version for nfs mount
Fixes #
```
feat: upgrade to aznfs 2.0.3 version for nfs mount
```
=> feat: upgrade to aznfs 2.0.3 version for nfs mount

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: generate sas token when secret is used in volume cloning
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1207
Fixes #
```
fix: generate sas token when secret is used in volume cloning
```
=> [release-1.23] fix: generate sas token when secret is used in volume cloning

docs/workload-identity-static-pv-mount.md
=> chore: Update workload-identity-static-pv-mount.md

pkg/blobplugin/Dockerfile, test/sanity/run-test.sh
/kind feature
feat: upgrade azcopy version to 10.22.2
Fixes #
```
none
```
=> feat: upgrade azcopy version to 10.22.2

pkg/blobplugin/Dockerfile, test/sanity/run-test.sh
/kind feature
feat: upgrade azcopy version to 10.22.2 for volume clone feature
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1219
Fixes #
```
none
```
=> [release-1.23] feat: upgrade azcopy version to 10.22.2 for volume clone feature

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go
/kind bug
fix: increase volume cloning timeout and reduce time cost
Fixes #1676
```
fix: increase volume cloning timeout and reduce time cost
```
=> fix: increase volume cloning timeout and reduce time cost

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, test/sanity/run-test.sh
/kind bug
fix: increase volume cloning timeout
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1226
Fixes #
```
none
```
=> [release-1.23] fix: increase volume cloning timeout

test/sanity/run-test.sh
/kind test
test: fix sanity test failure
Fixes #
```
none
```
=> test: fix sanity test failure

pkg/blobplugin/Dockerfile
/kind feature
feat: upgrade to aznfs 2.0.4 version for nfs mount
Fixes #
```
feat: upgrade to aznfs 2.0.4 version for nfs mount
```
=> feat: upgrade to aznfs 2.0.4 version for nfs mount

pkg/blob/azure.go, pkg/blob/azure_test.go, pkg/blob/controllerserver.go, pkg/blob/nodeserver.go
/kind bug
fix: panic when controller does not have cloud config
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1250
Fixes #
```
fix: panic when controller does not have cloud config
```
=> [release-1.22] fix: panic when controller does not have cloud config

deploy/csi-blob-driver.yaml
=> chore: Update csi-blob-driver.yaml

deploy/v1.23.3/csi-blob-driver.yaml, deploy/v1.24.0/csi-blob-driver.yaml
/kind bug
fix: add tokenRequests on v1.23.3, v1.24.0 in kubectl install
Fixes #1240
```
fix: add tokenRequests on v1.23.3, v1.24.0 in kubectl install
```
=> fix: add tokenRequests on v1.23.3, v1.24.0 in kubectl install

pkg/blob/azure.go
/kind bug
fix: ensure azure cloud config could be loaded from secret
Fixes #
```
fix: ensure azure cloud config could be loaded from secret
```
=> fix: ensure azure cloud config could be loaded from secret

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go, test/e2e/dynamic_provisioning_test.go
/kind feature
feat: provide nfsv3 protocol to enforce nfs mount
when we specify `protocol: nfsv3` in storage class or pv, this driver would enforce with nfs protocol instead of using aznfs mount by default, that provides a workaround when aznfs mount does not work
Fixes #
```
feat: provide nfsv3 protocol to enforce nfs mount
```
=> feat: provide nfsv3 protocol to enforce nfs mount

pkg/blobplugin/Dockerfile, test/sanity/run-test.sh
/kind feature
feat: upgrade azcopy version to 10.23.0 for volume clone feature
```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Server: Kestrel
Location: https://azcopyvnext.azureedge.net/releases/release-10.23.0-20240129/azcopy_linux_amd64_10.23.0.tar.gz
```
Fixes #
```
feat: upgrade azcopy version to 10.23.0 for volume clone feature
```
=> feat: upgrade azcopy version to 10.23.0 for volume clone feature

pkg/blob/nodeserver.go
/kind bug
fix: nfs mount stuck issue
original `wait.PollImmediate` may be stuck if nfs mount is stuck, this PR fixes the issue
Fixes #
```
fix: nfs mount stuck issue
```
=> fix: nfs mount stuck issue

pkg/blob/blob.go, pkg/blob/controllerserver.go
/kind bug
chore: only use sas token for azcopy when useDataPlaneAPI is used
Fixes #
```
none
```
=> chore: only use sas token for azcopy when useDataPlaneAPI is used

pkg/blob/controllerserver.go, pkg/blob/nodeserver.go, pkg/util/util.go, pkg/util/util_test.go
/kind cleanup
cleanup: rename WaitUntilTimeout func
Fixes #
```
none
```
=> cleanup: rename WaitUntilTimeout func

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind cleanup
chore: refine sastoken cache
Fixes #
```
none
```
=> chore: refine sastoken cache

pkg/blob/azure.go, pkg/blob/azure_test.go
/kind bug
The same fix as https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2233
Fixes #
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2233
```
fix: workload identity did not work
```
=> fix: workload identity did not work

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/options.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/transport.go
/kind bug
fix: enable http with track2 sdk
related to fix: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5831
Fixes #
```
fix: enable http with track2
```
=> fix: enable http with track2 sdk

charts/latest/blob-csi-driver/templates/csi-blob-node.yaml, pkg/blobfuse-proxy/init.sh, pkg/blobfuse-proxy/install-proxy-rhcos.sh, pkg/blobfuse-proxy/install-proxy.sh
This is a cherry-pick of #1325
=> [release-1.24] feat: support setting kubelet path for blobfuse-proxy endpoint

go.mod, go.sum, pkg/blob/nodeserver.go, vendor/modules.txt, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/util.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/accesscontrol.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/configuration.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil/prefix.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/securitygroup/securitygroup.go, vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
/kind cleanup
chore: set node_get_volume_stats log level to 6
Fixes #
```
none
```
=> chore: set node_get_volume_stats log level to 6

pkg/blobplugin/Dockerfile
/kind feature
feat: upgrade to aznfs 2.0.7 version for nfs mount
Fixes #
```
feat: upgrade to aznfs 2.0.7 version for nfs mount
```
=> feat: upgrade to aznfs 2.0.7 version for nfs mount

pkg/blobfuse-proxy/install-proxy-rhcos.sh, pkg/blobfuse-proxy/install-proxy.sh
/kind bug
fix: force copy blobfuse2 binary to avoid Text file busy error
Fixes #1405
```
fix: force copy blobfuse2 binary to avoid Text file busy error
```
=> fix: force copy blobfuse2 binary to avoid Text file busy error

pkg/blob/nodeserver.go
/kind bug
fix: override aznfs AZURE_ENDPOINT_OVERRIDE
this could fix aznfs mount failure in airgaped cloud
Fixes #
```
fix: override aznfs AZURE_ENDPOINT_OVERRIDE
```
=> fix: override aznfs AZURE_ENDPOINT_OVERRIDE

pkg/blobfuse-proxy/install-proxy-rhcos.sh, pkg/blobfuse-proxy/install-proxy.sh
This is a cherry-pick of #1425
=> [release-1.23] fix: force copy blobfuse2 binary to avoid Text file busy error

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/util/util.go, pkg/util/util_test.go
/kind feature
feat: add tag value delimiter parameter and allow tag values containing commas and equal sign
referring to azuredisk csi driver issue https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2323
Fixes #
```
none
```
=> feat: add tag value delimiter

pkg/blob/nodeserver.go
/kind cleanup
cleanup: logs refine
Fixes #
```
none
```
=> cleanup: refine logs

pkg/blob/nodeserver.go
/kind cleanup
cleanup: logs refine
Fixes #
```
none
```
=> [release-1.23] cleanup: refine logs

pkg/blob/nodeserver.go
/kind cleanup
cleanup: logs refine
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1473
Fixes #
```
none
```
=> [release-1.23] cleanup: refine log

docs/driver-parameters.md, pkg/blob/blob.go, pkg/blob/controllerserver.go, test/e2e/dynamic_provisioning_test.go
/kind feature
[release-1.23] feat: add allowSharedKeyAccess parameter
cherry-pick for https://github.com/kubernetes-sigs/blob-csi-driver/pull/1470
Fixes #
```
none
```
=> [release-1.23] feat: add allowSharedKeyAccess parameter

pkg/blob/controllerserver_test.go
/kind test
test: add allowSharedKeyAccess feature unit test for pr: https://github.com/kubernetes-sigs/blob-csi-driver/pull/1470
Fixes #
```
none
```
=> test: add allowSharedKeyAccess feature unit test

pkg/blob/controllerserver.go
/kind feature
feat: add metadata in container creating by csi driver, `createdBy: blob.csi.azure.com`.
Fixes #
test result:
The first used dataplane api
```
none
```
=> feat: add metadata tag on the storage account created by the driver

pkg/blobfuse-proxy/server/server.go
/kind bug
fix: mout failed by blobfuse2 in azure linux v3
Fixes #
azurelinux v2(mariner) node:
azurelinux v3 node:
```
fix: mout failed by blobfuse2 in azure linux v3
```
=> fix: blobfuse mount failure in Azure Linux v3

pkg/blobfuse-proxy/install-proxy.sh
/kind bug
fix: ignore specific blobfuse version install failure
when the node has a higher blobfuse2 version installed, install a lower blobfuse2 version in initContainer would fail, this PR ignores the error and make CSI driver keep running
Fixes #1507
```
fix: ignore specific blobfuse version install failure
```
=> fix: ignore specific blobfuse version install failure

pkg/blob/controllerserver.go
/kind cleanup
cleanup: refine copy volume logic
Fixes #
```
none
```
=> cleanup: refine copy volume logic

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
/kind bug
fix: VirtualNetworkRule match issue during account search
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1541
Fixes #
```
fix: VirtualNetworkRule match issue during account search
```
=> [release-1.24] fix: VirtualNetworkRule match issue during account search

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind cleanup
cherrypick for https://github.com/kubernetes-sigs/blob-csi-driver/pull/1521 and https://github.com/kubernetes-sigs/blob-csi-driver/pull/1550
Fixes #
```
none
```
=> [release-1.23] cleanup: refactor volume cloning

pkg/blobplugin/Dockerfile
=> fix: CVE-2024-38428 remove wget to close vuln, reduce image size

.github/workflows/static.yaml, pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go, pkg/csi-common/utils.go, pkg/csi-common/utils_test.go, test/e2e/dynamic_provisioning_test.go, test/e2e/suite_test.go
=> cleanup: fix golint errors

pkg/blobplugin/Dockerfile
/kind feature
chore: upgrade to debian-base:bookworm-v1.0.4 base image
Fixes #
```
none
```
=> chore: upgrade to debian-base:bookworm-v1.0.4 base image

pkg/blobplugin/Dockerfile
/kind feature
chore: upgrade to debian-base:bookworm-v1.0.4 base image
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1575
Fixes #
```
none
```
=> [release-1.22] chore: upgrade to debian-base:bookworm-v1.0.4 base image

go.mod
cleanup: fix golint error
Fixes #
```
none
```
=> [release-1.23] cleanup: fix golint error

go.mod
cleanup: fix golint error
Fixes #
```
none
```
=> [release-1.22] cleanup: fix golint error

.github/workflows/static.yaml, pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, pkg/blob/nodeserver.go, pkg/csi-common/utils_test.go, test/e2e/dynamic_provisioning_test.go, test/e2e/suite_test.go
=> [release-1.22] cleanup: upgrade golint version and fix golint errors

pkg/blobfuse-proxy/server/server.go
/kind bug
fix: inherit os environment when calling blobfuse2 in blobfuse-proxy
blobfuse2 mount support environment variables, while since blobfuse-proxy does not inherit os environment when calling blobfsue2 mount, the environment variables could not be injected to the blobfuse2, this PR fixes the issue.
Fixes #
```
fix: inherit os environment when calling blobfuse2 in blobfuse-proxy
```
=> fix: inherit os environment when calling blobfuse2 in blobfuse-proxy

pkg/blobplugin/Dockerfile
/kind bug
fix: nfs mount failure on arm64 node
the bug was introduced by https://github.com/kubernetes-sigs/blob-csi-driver/pull/1572
Fixes #
```
fix: nfs mount failure on arm64 node
```
=> fix: nfs mount failure on arm64 node

deploy/csi-blob-node.yaml, deploy/example/cloning/nginx-pod-restored-cloning.yaml, deploy/example/deployment-nfs.yaml, deploy/example/deployment.yaml, deploy/example/nfs/statefulset.yaml, deploy/example/nginx-blobfuse-inline-volume.yaml, deploy/example/nginx-pod-blob.yaml, deploy/example/statefulset-nfs.yaml, deploy/example/statefulset.yaml
/kind cleanup
chore: enable blobfuse-proxy by default in kubectl install
Fixes #
```
none
```
=> chore: enable blobfuse-proxy by default in kubectl install

pkg/blobfuse-proxy/install-proxy.sh
/kind feature
fix: install blobfuse2 on arm64 node by blobfuse-proxy
Fixes #
```
fix: install blobfuse2 on arm64 node by blobfuse-proxy
```
=> fix: install blobfuse2 on arm64 node by blobfuse-proxy

pkg/blobfuse-proxy/install-proxy-rhcos.sh, pkg/blobfuse-proxy/install-proxy.sh
/kind bug
fix: skip blobfuse-proxy copy if it's not enabled in driver init
Fixes #1645
```
fix: skip blobfuse-proxy copy if it's not enabled in driver init
```
=> fix: skip blobfuse-proxy copy if it's not enabled in driver init

pkg/blobplugin/Dockerfile
/kind bug
fix: blobfuse install failure in install-blobfuse-proxy initContainer
Fixes #1658
```
fix: blobfuse install failure in install-blobfuse-proxy initContainer
```
=> fix: blobfuse install failure in install-blobfuse-proxy initContainer

test/utils/azure/azure_helper.go
/kind test
Add UA for e2e client
Fixes #
```
none
```
=> test: add UserAgent for e2e client

pkg/blob/blob.go
/kind bug
fix: tagValueDelimiter parameter mismatch
Fixes #
```
fix: tagValueDelimiter parameter mismatch
```
=> fix: tagValueDelimiter parameter mismatch

.github/dependabot.yaml
/kind test
Group all deps update into one pr.
Fixes #
```
none
```
=> Group all deps update into one pr.

pkg/blobfuse-proxy/install-proxy-rhcos.sh, pkg/blobfuse-proxy/install-proxy.sh
/kind bug
fix: always start blobfuse-proxy as long as it's enabled, this could fix the issue in case blobfuse-proxy is not started after installation.
Fixes #1718
```
fix: always start blobfuse-proxy as long as it's enabled
```
=> fix: always start blobfuse-proxy as long as it's enabled

test/sanity/run-tests-all-clouds.sh
/kind cleanup
test: upgrade csi-test to v5.3.1 in sanity test
Fixes #
```
none
```
=> test: upgrade csi-test to v5.3.1 in sanity test

.github/dependabot.yaml
Reverts kubernetes-sigs/blob-csi-driver#1708
=> Revert "Group all deps update into one pr."

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: wait for azcopy job running in volume clone
Fixes #
```
fix: wait for azcopy job running in volume clone
```
=> fix: wait for azcopy job running in volume clone

pkg/blobplugin/main.go, pkg/blobplugin/main_test.go
/kind test
test: add unit test for main function
Fixes #
```
none
```
=> test: add unit test for main function

.github/workflows/linux.yaml
/kind test
test: exclude some go fake files in ut coverage
Fixes #
```
none
```
=> test: exclude some go fake files in ut coverage

pkg/blobplugin/Dockerfile, test/sanity/run-test.sh
/kind cleanup
chore: fix azcopy download error
Fixes #
```
none
```
=> chore: fix azcopy download error

charts/README.md
doc: fix helm chart install
Fixes #1802
```
none
```
=> doc: fix helm chart install

charts/index.yaml
/kind bug
fix: helm chart index
Fixes #1802
```
none
```
=> fix: helm chart index

deploy/example/blobfuse-mi/README.md, deploy/example/blobfuse-mi/pv-blobfuse-mi.yaml, deploy/example/e2e_usage.md, deploy/example/pv-blobfuse-auth.yaml, deploy/example/pv-blobfuse-csi-keyvault.yaml, deploy/example/pv-blobfuse-csi.yaml, deploy/example/pv-blobfuse-nfs.yaml, docs/workload-identity-static-pv-mount.md
doc: fix volumeHandle doc
Fixes #
```
none
```
=> doc: fix volumeHandle doc

go.mod, go.sum, vendor/k8s.io/kubernetes/pkg/features/kube_features.go, vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go, vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go, vendor/k8s.io/kubernetes/test/e2e/framework/debug/resource_usage_gatherer.go, vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go, vendor/k8s.io/kubernetes/test/e2e/framework/framework.go, vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go, vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go, vendor/k8s.io/kubernetes/test/utils/density_utils.go, vendor/k8s.io/kubernetes/test/utils/deployment.go, vendor/k8s.io/kubernetes/test/utils/image/manifest.go, vendor/k8s.io/kubernetes/test/utils/runners.go, vendor/modules.txt
/kind bug
fix: CVE-2025-0426
```
Total: 1 (UNKNOWN: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌───────────────────┬───────────────┬──────────┬────────┬───────────────────┬──────────────────────────────────┬────────────────────────────────────────────────────────┐
│      Library      │ Vulnerability │ Severity │ Status │ Installed Version │          Fixed Version           │                         Title                          │
├───────────────────┼───────────────┼──────────┼────────┼───────────────────┼──────────────────────────────────┼────────────────────────────────────────────────────────┤
│ k8s.io/kubernetes │ CVE-2025-0426 │ MEDIUM   │ fixed  │ v1.31.3           │ 1.32.2, 1.31.6, 1.30.10, 1.29.14 │ k8s.io/kubernetes: …
```
=> fix: CVE-2025-0426

pkg/blob/blob.go, pkg/blob/controllerserver.go, pkg/util/util.go, pkg/util/util_test.go
/kind bug
fix: cleanup azcopy jobs after job complete
this could reduce .azopy/plans folder files
Fixes #
```
fix: cleanup azcopy jobs after job complete
```
=> fix: cleanup azcopy jobs after job complete

pkg/blobplugin/Dockerfile
/kind feature
feat: upgrade aznfs package to v2.0.11
Fixes #
```
feat: upgrade aznfs package to v2.0.11
```
=> feat: upgrade aznfs package to v2.0.11

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
/kind bug
fix: CVE-2024-51744
```
blobfuse-proxy/blobfuse-proxy (gobinary)
Total: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
â”‚           Library            â”‚ Vulnerability  â”‚ Severity â”‚ Installed Version â”‚ Fixed Version â”‚                       Title …
```
=> [release-1.24] fix: CVE-2024-51744

pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: storageEndPointSuffix setting in on-prem cluster
if only `storageEndpointSuffix` is specified in sc in on-prem cluster, create blob container should work with this PR.
Fixes #1926
```
none
```
=> fix: storageEndPointSuffix setting in on-prem cluster

docs/driver-parameters.md
doc: add ClientID parameter in doc
Fixes #
```
none
```
=> doc: add ClientID parameter in doc

pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go, test/e2e/testsuites/testsuites.go
/kind cleanup
cleanup: remove deprecated wait.PollImediate function
Fixes #
```
none
```
=> cleanup: remove deprecated wait.PollImediate function

go.mod, pkg/util/util.go, pkg/util/util_test.go, vendor/go.uber.org/goleak/.gitignore, vendor/go.uber.org/goleak/.golangci.yml, vendor/go.uber.org/goleak/CHANGELOG.md, vendor/go.uber.org/goleak/LICENSE, vendor/go.uber.org/goleak/Makefile, vendor/go.uber.org/goleak/README.md, vendor/go.uber.org/goleak/doc.go, vendor/go.uber.org/goleak/internal/stack/doc.go, vendor/go.uber.org/goleak/internal/stack/scan.go, vendor/go.uber.org/goleak/internal/stack/stacks.go, vendor/go.uber.org/goleak/leaks.go, vendor/go.uber.org/goleak/options.go, vendor/go.uber.org/goleak/testmain.go, vendor/go.uber.org/goleak/tracestack_new.go, vendor/modules.txt
/kind bug
fix: goroutine leak when timeout
https://github.com/kubernetes-sigs/blob-csi-driver/pull/1947
Fixes #
```
fix: goroutine leak when timeout
```
=> [release-1.26] fix: goroutine leak when timeout

go.mod, pkg/util/util.go, pkg/util/util_test.go, vendor/go.uber.org/goleak/.gitignore, vendor/go.uber.org/goleak/.golangci.yml, vendor/go.uber.org/goleak/CHANGELOG.md, vendor/go.uber.org/goleak/LICENSE, vendor/go.uber.org/goleak/Makefile, vendor/go.uber.org/goleak/README.md, vendor/go.uber.org/goleak/doc.go, vendor/go.uber.org/goleak/internal/stack/doc.go, vendor/go.uber.org/goleak/internal/stack/scan.go, vendor/go.uber.org/goleak/internal/stack/stacks.go, vendor/go.uber.org/goleak/leaks.go, vendor/go.uber.org/goleak/options.go, vendor/go.uber.org/goleak/testmain.go, vendor/go.uber.org/goleak/tracestack_new.go, vendor/modules.txt
/kind bug
fix: goroutine leak when timeout
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1947
Fixes #
```
fix: goroutine leak when timeout
```
=> [release-1.24] fix: goroutine leak when timeout

go.mod, pkg/util/util.go, pkg/util/util_test.go, vendor/go.uber.org/goleak/.gitignore, vendor/go.uber.org/goleak/.golangci.yml, vendor/go.uber.org/goleak/CHANGELOG.md, vendor/go.uber.org/goleak/LICENSE, vendor/go.uber.org/goleak/Makefile, vendor/go.uber.org/goleak/README.md, vendor/go.uber.org/goleak/doc.go, vendor/go.uber.org/goleak/internal/stack/doc.go, vendor/go.uber.org/goleak/internal/stack/scan.go, vendor/go.uber.org/goleak/internal/stack/stacks.go, vendor/go.uber.org/goleak/leaks.go, vendor/go.uber.org/goleak/options.go, vendor/go.uber.org/goleak/testmain.go, vendor/go.uber.org/goleak/tracestack_new.go, vendor/modules.txt
/kind bug
fix: goroutine leak when timeout
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1947
Fixes #
```
fix: goroutine leak when timeout
```
=> [release-1.25] fix: goroutine leak when timeout

pkg/blob/nodeserver.go
/kind bug
fix: grpc connection was not closed properly
Fixes #
```
fix: grpc connection was not closed properly
```
=> fix: grpc connection was not closed properly

pkg/blob/nodeserver.go
/kind bug
fix: incorrect metris log in NodeStageVolume
Fixes #
```
none
```
=> fix: incorrect metris log in NodeStageVolume

deploy/example/vpa/README.md, deploy/example/vpa/install-components/admission-controller-deployment.yaml, deploy/example/vpa/install-components/delete-webhook.sh, deploy/example/vpa/install-components/gencerts.sh, deploy/example/vpa/install-components/recommender-deployment.yaml, deploy/example/vpa/install-components/rmcerts.sh, deploy/example/vpa/install-components/updater-deployment.yaml, deploy/example/vpa/install-components/vpa-rbac.yaml, deploy/example/vpa/install-components/vpa-v1-crd-gen.yaml, deploy/example/vpa/install-components/warn-obsolete-vpa-objects.sh, deploy/example/vpa/install-vpa.sh, deploy/example/vpa/uninstall-vpa.sh, deploy/example/vpa/vertical-pod-autoscaler.yaml, hack/verify-yamllint.sh
/kind feature
feat: add VerticalPodAutoscaler to blob csi controller pod
Fixes #
```
none
```
=> feat: add VerticalPodAutoscaler to blob csi controller pod

docs/workload-identity-deploy-csi-driver.md
doc: Remove the obsolete comment to avoid confusing the user into thinking that workload identity is not supported by the AKS-managed Blob CSI driver.
Fixes #
```
none
```
=> doc: Remove the obsolete comment

pkg/blobplugin/Dockerfile
/kind cleanup
cleanup: refine Dockerfile
Fixes #
```
none
```
=> cleanup: refine Dockerfile

docs/workload-identity-static-pv-mount.md, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: add mountWithWorkloadIdentityToken parameter
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1988
Fixes #
```
fix: add mountWithWorkloadIdentityToken parameter
```
=> [release-1.25] fix: add mountWithWorkloadIdentityToken parameter

docs/workload-identity-static-pv-mount.md, pkg/blob/blob.go, pkg/blob/blob_test.go, pkg/blob/controllerserver.go, pkg/blob/controllerserver_test.go
/kind bug
fix: add mountWithWorkloadIdentityToken parameter
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1988
https://github.com/kubernetes-sigs/blob-csi-driver/pull/1798 has token expire issue(managed identity token expires in 24h), this PR changes the behavior, disables mounting with token by default
Fixes #
```
fix: add mountWithWorkloadIdentityToken parameter
```
=> [release-1.26] fix: add mountWithWorkloadIdentityToken parameter

pkg/blobplugin/Dockerfile
/kind feature
chore: upgrade to aznfs v2.0.12
Fixes #
```
none
```
=> chore: upgrade to aznfs v2.0.12

go.mod, pkg/blob/azure.go, pkg/blob/azure_test.go
/kind cleanup
cleanup: remove unused getCloudEnvironment func
Fixes #
```
none
```
=> cleanup: remove unused getCloudEnvironment func

pkg/blobfuse-proxy/server/server.go
/kind cleanup
cleanup: disable version check in blobfuse2 driver by default
rework of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1994
Fixes #
```
cleanup: disable version check in blobfuse2 driver by default
```
=> cleanup: disable version check in blobfuse2 driver by default

.github/workflows/static.yaml, pkg/csi-common/driver.go, pkg/csi-common/utils.go, pkg/csi-common/utils_test.go
test: fix golint errors
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/2037
Fixes #
```
none
```
=> [release-1.23] test: fix golint errors

charts/index.yaml
/kind bug
fix: helm chart index on release-1.25
Fixes #
```
none
```
=> [release-1.25] chore: fix helm chart index on release-1.25

pkg/blob/blob.go, pkg/blob/blob_test.go
/kind feature
feat: use kubelet identity by default in msi auth
Fixes #
```
feat: use kubelet identity by default in msi auth
```
=> feat: use kubelet identity by default in msi auth

go.mod, go.sum, vendor/golang.org/x/oauth2/LICENSE, vendor/golang.org/x/oauth2/README.md, vendor/golang.org/x/oauth2/internal/doc.go, vendor/golang.org/x/oauth2/internal/oauth2.go, vendor/golang.org/x/oauth2/internal/token.go, vendor/golang.org/x/oauth2/internal/transport.go, vendor/golang.org/x/oauth2/oauth2.go, vendor/golang.org/x/oauth2/pkce.go, vendor/golang.org/x/oauth2/token.go, vendor/golang.org/x/oauth2/transport.go, vendor/modules.txt
/kind bug
fix: CVE-2025-22868
Fixes #
```
fix: CVE-2025-22868
```
=> [release-1.23] fix: CVE-2025-22868

hack/verify-helm-chart-index.sh
test: ignore latest tgz file in helm chart index verification
Fixes #
```
none
```
=> test: ignore latest tgz file in helm chart index verification
