- pkg/blobfuse/nodeserver.go
/kind bug
According to https://github.com/Azure/azure-storage-fuse/issues/267, two different blobfuse mount use same `tmp-path` value on same node would have race condition, this PR use a different `tmp-path` value for every blobfuse mount
Fixes #
@seguler
```
use different tmp-path value for different blobfuse mounts
```
> use different tmp-path value for different blobfuse mounts

- Gopkg.lock
- Makefile
- pkg/blobfuse/blobfuse.go
- pkg/blobfuse/version.go
- pkg/blobfuseplugin/main.go
This commit adds version flag in blobfuse csi file driver.
Output of `--version` flag:
```
ashishranjan738@Ashish-PC:~/Project/go/src/github.com/csi-driver/blobfuse-csi-driver$ ./_output/blobfuseplugin --version
Build Date: "2019-04-24T02:41:27Z"
Compiler: gc
Driver Name: blobfuse.csi.azure.com
Driver Version: v0.1.0-alpha2
Git Commit: 3d525e3cf4a221d7adae2062d4c248aed00ee9d2
Go Version: go1.12.1
Platform: linux/amd64
```
Output of streaming logs:
```
ashishranjan738@Ashish-PC:~/Project/go/src/github.com/csi-driver/blobfuse-csi-driver$ ./_output/blobfuseplugin --nodeid 6
I0424 08:41:47.345529   23895 blobfuse.go:67] 
DRIVER INFORMATION:
-------------------
Build Date: "2019-04-24T02:41:27Z"
Compiler: gc
Driver Name: blobfuse.csi.azure.com
Driver …
```
> enhance(version): adds version flag in blobfuse csi file driver

- charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
- deploy/csi-blobfuse-node.yaml
- pkg/blobfuse/nodeserver.go
/kind bug
Each parameter in cmd should be separated with a blank. Otherwise, it won't work.
Fixes #25 
```
fix: enable mount options
```
> fix: enable mount options

- Gopkg.lock
- Gopkg.toml
- pkg/blobfuseplugin/main.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
/kind feature
With this feature, we can get the prometheus metrics of azure_api.
- update the vendor "github.com/prometheus/client_golang"
- set the default metrics port to 10252
Fixes #64 
```
export prometheus metrics
```
> feat: export prometheus metrics

- charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
- charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
- deploy/csi-blobfuse-controller.yaml
- deploy/csi-blobfuse-node.yaml
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind flake
We need to set resource requests/limits for blobfuse csi driver pods.
Fixes #
```
setting cpu/memory resource limits for blobfuse csi driver
```
> set cpu/memory resource limits for blobfuse csi driver

- Makefile
- deploy/example/blobfuse-deployment.yaml
- deploy/example/blobfuse-statefulset.yaml
- pkg/blobfuse/blobfuse.go
- pkg/blobfuse/blobfuse_test.go
- pkg/blobfuse/nodeserver.go
/kind bug
This PR together with an k8s upstream PR(https://github.com/kubernetes/kubernetes/pull/88569) would fix the  corrupted mount issue when fuse based CSI driver daemonset is restarted on the node:
after daemonset is restarted, original blobfuse mount is broken, this PR would handle broken mount in both `NodeStage` and `NodePublish`
- detect the broken mount path
- unmount broken mount path
- remount mount path
Fixes #115
Main fix is in `ensureMountPoint` func:
```
func (d *Driver) ensureMountPoint(target string) error {
notMnt, err := d.mounter.IsLikelyNotMountPoint(target)
if err != nil && !os.IsNotExist(err) {
if IsCorruptedDir(target) { …
```
> fix corrupted mount issue when driver daemonset restarted

- pkg/blobfuse/blobfuse.go
- pkg/blobfuse/blobfuse_test.go
- pkg/blobfuse/controllerserver.go
- test/e2e/driver/blobfuse_csi_driver.go
- test/e2e/driver/driver.go
- test/e2e/pre_provisioning_test.go
- test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
/kind test
Ref: [Option#1: use existing credentials in k8s cluster](https://github.com/kubernetes-sigs/blobfuse-csi-driver/blob/master/deploy/example/e2e_usage.md#option1-use-existing-credentials-in-k8s-cluster)
Fixes #80 
```
```
> test: add the e2e test "use existing credentials in k8s cluster"

- pkg/blobfuse/blobfuse.go
- pkg/blobfuse/nodeserver.go
- test/e2e/driver/blobfuse_csi_driver.go
- test/e2e/driver/driver.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/pre_provisioning_test.go
- test/e2e/suite_test.go
- test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
- test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
- test/e2e/testsuites/specs.go
- test/e2e/testsuites/testsuites.go
/kind test
Ref: [Option#2: provide storage account name and key(or sastoken)](https://github.com/kubernetes-sigs/blobfuse-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-provide-storage-account-name-and-keyor-sastoken)
Fixes #80 
```
add the e2e test "should use provided credentials"
```
> test: add the e2e test "should use provided credentials"

- Makefile
- charts/latest/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
- charts/latest/blobfuse-csi-driver/values.yaml
- charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
- charts/v0.1.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
- charts/v0.1.0/blobfuse-csi-driver/values.yaml
- charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
- charts/v0.2.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
- charts/v0.2.0/blobfuse-csi-driver/values.yaml
- charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-controller.yaml
- charts/v0.3.0/blobfuse-csi-driver/templates/csi-blobfuse-node.yaml
- charts/v0.3.0/blobfuse-csi-driver/values.yaml
- charts/v0.4.0/blobfuse-csi-driver/values.yaml
- deploy/csi-blobfuse-controller.yaml
- deploy/csi-blobfuse-node.yaml
- deploy/v0.1.0/csi-blobfuse-controller.yaml
- deploy/v0.1.0/csi-blobfuse-node.yaml
- deploy/v0.2.0/csi-blobfuse-controller.yaml
- deploy/v0.2.0/csi-blobfuse-node.yaml
- deploy/v0.3.0/csi-blobfuse-controller.yaml
- deploy/v0.3.0/csi-blobfuse-node.yaml
- deploy/v0.4.0/csi-blobfuse-controller.yaml
- deploy/v0.4.0/csi-blobfuse-node.yaml
/kind bug
This PR
- change `imagePullPolicy` from `Always` to `IfNotPresent`([default value](https://kubernetes.io/docs/concepts/containers/images/#updating-images)), this PR could save around 1min for start up CSI driver deamonset pod on new VMSS node on AKS (with autoscaler enabled)
- make node daemonset ignore taint
- change `csi-node-driver-registrar` version to `v1.2.0`
Fixes #
```
none
```
> fix: change imagePullPolicy to IfNotPresent

- deploy/example/pv-blobfuse-csi.yaml
- deploy/example/storageclass-blobfuse-csi-existing-container.yaml
- docs/driver-parameters.md
- pkg/blobfuse/blobfuse.go
- pkg/blobfuse/nodeserver.go
/kind feature
feat: add storage account private link support
With this PR, user could specify a self-defined account address in azure file storage class setting:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: blob
provisioner: blobfuse.csi.azure.com
parameters:
skuName: Standard_LRS  # available values: Standard_LRS, Standard_GRS, Standard_RAGRS
resourceGroup: EXISTING_RESOURCE_GROUP
storageAccount: EXISTING_STORAGE_ACCOUNT
server: SERVER_ADDRESS  # optional, provide a new address to replace default "accountname.blob.core.windows.net"
reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate
```
Fixes …
> feat: add storage account private link support

- test/e2e/dynamic_provisioning_test.go
- test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
- test/e2e/testsuites/testsuites.go
- vendor/k8s.io/kubernetes/test/e2e/framework/events/BUILD
- vendor/k8s.io/kubernetes/test/e2e/framework/events/events.go
- vendor/modules.txt
/kind test
test: add negative mount options e2e test
blocked by :
```
Verifying gofmt
No issue found
Verifying govet
test/e2e/testsuites/testsuites.go:535:4: cannot use t.client (type "sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/client-go/kubernetes".Interface) as type "k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes".Interface in argument to "k8s.io/kubernetes/test/e2e/framework/events".WaitTimeoutForEvent:
"sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/client-go/kubernetes".Interface does not implement "k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes".Interface (missing AdmissionregistrationV1 method)
```
Fixes #96  …
> test: add negative mount options e2e test

- charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
- charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
- deploy/csi-blob-controller.yaml
- deploy/csi-blob-node.yaml
/kind flake
Set the reasonable CPU and Memory.
- Reduce limit of azurefile container CPU and Memory to one fifth.
- 
- Reduce limit of sidecar containers CPU and Memory to one tenth.
Fixes #
Use `kubectl top pod` command to get the usage data.
```
POD                                    NAME              CPU(cores)   MEMORY(bytes)   
csi-blob-controller-59f965c9b9-58lf4   csi-attacher      1m           8Mi             
csi-blob-controller-59f965c9b9-58lf4   csi-provisioner   1m           9Mi             
csi-blob-controller-59f965c9b9-58lf4   liveness-probe    1m           4Mi             
csi-blob-controller-59f965c9b9-58lf4   blob …
```
> chore: reduce limit of CPU and Memory

- pkg/blob/nodeserver.go
/kind bug
fix: use timestamp for tmp-path
fixed below issue:
```
Warning  FailedMount       37s (x7 over 101s)  kubelet, aks-agentpool-23717925-vmss000000  MountVolume.MountDevice failed for volume "pvc-432e1e6f-103f-4df5-befa-1546aab8f030" : rpc error: code = Unknown
desc = Mount failed with error: exit status 1, output: Error: temp directory '/mnt/mc_supaksrg_supaks_eastus#fuse14c9db7416f94784ae3#pvc-432e1e6f-103f-4df5-befa-1546aab8f030' is not empty. blobfuse needs
an empty temp directory
count of dir entries 3
```
Fixes #
```
fix: use timestamp for tmp-path
```
> fix: use timestamp for tmp-path

- deploy/example/storageclass-blob-secret.yaml
- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver.go
/kind feature
feat: bring your own account key
In some scenarios, user's cluster does not have permission to a storage account(in some case, the storage account is in another subscription), we already provide static provisioning for that scenario. While that's not enough, user still wants to only bring own storage account key and driver could provide storage class support(dynamic provisioning).
CSI driver already supports specifying secret in every CSI methods.
- create `azure-secret` to store account name & key
```
kubectl create secret generic azure-secret --from-literal accountname=NAME --from-literal accountkey="KEY" --type=Opaque
```
- create azure file storage class referencing `azure-secret` in create/delete/mount …
> feat: bring your own account key for dynamic provisioning

- charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
- deploy/csi-blob-node.yaml
/kind bug
fix: increase CPU limit for throttling issue
as I tested, following `dd` test could consume around 200% CPU, original `200m` limit setting could cause CPU throttling.
```console
Filesystem      Size  Used Avail Use% Mounted on
overlay         124G   12G  113G  10% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
blobfuse        197G  2.1G  185G   2% /mnt/blob
/dev/sda1       124G   12G  113G  10% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            16G   12K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G …
```
> fix: increase CPU limit for throttling issue

- charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
- charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
- deploy/csi-blob-controller.yaml
- deploy/csi-blob-node.yaml
- pkg/blobplugin/Dockerfile
- pkg/blobplugin/dev.Dockerfile
/kind bug
fix: create nonroot user in Dockerfile
Fixes #
```
fix: create nonroot user in Dockerfile
```
> fix: create nonroot user in Dockerfile

- .github/workflows/windows.yaml
- pkg/blob/nodeserver_test.go
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
enable windows unit tests
Fixes #253
```
none
```
> test: enable windows unit tests

- charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
- charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
- deploy/csi-blob-controller.yaml
- deploy/csi-blob-node.yaml
- pkg/blobplugin/Dockerfile
- pkg/blobplugin/dev.Dockerfile
Reverts kubernetes-sigs/blob-csi-driver#252
Original PR did not improve the security, that PR is just for bypass security scanning, while would introduce various permission setting issue.
> Revert "fix: create nonroot user in Dockerfile"

- .github/workflows/darwin.yaml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yaml
- Makefile
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
enable unit tests for MacOS
Fixes #
```
none
```
> CI: enable unit tests for MacOS

- pkg/blob/blob.go
- pkg/blob/blob_test.go
/kind feature
feat: support arbitrary volume id
Currently in static pv, if there is no secret provided, volume id format must be `rg#accoutname#containername`, actually it's not necessary, if user provides following parameters, volume id could be arbitrary string:
```yaml
csi:
driver: blob.csi.azure.com
readOnly: false
volumeHandle: uniqe-volumeid  # make sure this volumeid is unique in the cluster
volumeAttributes:
resourceGroup: EXISTING_RESOURCE_GROUP_NAME
storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
containerName: EXISTING_CONTAINER_NAME
nodeStageSecretRef:
name: azure-secret
namespace: default
```
Fixes #291 …
> feat: support arbitrary volume id

- charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
- charts/latest/blob-csi-driver/values.yaml
- deploy/csi-blob-controller.yaml
/kind feature
chore: upgrade resizer to v1.1.0
Fixes #
```
--handle-volume-inuse-error <true/false>: Enable or disable volume-in-use error handling in external-resizer. Defaults to true and resize-controller will watch for all pods in all namespaces to check if PVC being expanded is in-use by a pod or not before retrying volume expansion if CSI driver throws volume-in-use error. Setting this to false will cause external-resizer to ignore volume-in-use error and resize-controller will retry volume expansion even if volume is already in use by a pod and CSI driver does not support expansion of in-use volumes. If CSI driver being used …
```
> chore: upgrade resizer to v1.1.0

- pkg/blob/blob.go
- pkg/blob/nodeserver.go
- pkg/blob/nodeserver_test.go
- pkg/blob/volume_lock.go
/kind bug
we don't correctly handle concurrent processing of NodeUnstage call if a previous NodeStage was in-progress and same thing applies to NodeUnpublish call too.
The specs says, if an operation is in-progress for the volume then SP should return error code "10 ABORTED".
Fixes #320 
```
none
```
```
none
```
> fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish

- charts/latest/blob-csi-driver/templates/csi-blob-controller.yaml
- charts/latest/blob-csi-driver/templates/csi-blob-node.yaml
- deploy/csi-blob-controller.yaml
- deploy/csi-blob-node.yaml
- pkg/blob/controllerserver.go
- pkg/csi-common/controllerserver-default.go
- pkg/csi-common/driver_test.go
- pkg/csi-common/identityserver-default.go
- pkg/csi-common/nodeserver-default.go
- pkg/csi-common/server.go
- pkg/csi-common/utils.go
- pkg/csi-common/utils_test.go
/kind bug
fix: reduce driver logs
- don't print follow method logs by default
following 3 method logs constitute 99.8% logs of all driver logs, this PR set the log level of following 3 methods as `10`, and it would not show in driver logs by default(<= `5` will show in driver logs)
```
/csi.v1.Identity/Probe
/csi.v1.Node/NodeGetCapabilities
/csi.v1.Node/NodeGetVolumeStats
```
- set log level of csi side car contains as 2
This could reduce `17,280` logs every day of csi-provisioner, csi-resizer, etc which has lease election, following logs would show every 5s:
```
I0119 12:57:02.073355       1 leaderelection.go:282] successfully renewed lease kube-system/blob-csi-azure-com
I0119 12:57:07.081182       1 …
```
> fix: reduce driver logs

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/nodeserver.go
- pkg/blobplugin/main.go
- test/e2e/suite_test.go
- test/integration/run-test.sh
- test/sanity/run-test.sh
test: use mock mount to fix sanity test failures
Fixes #
```
none
```
> test: use mock mount to fix sanity test failures

- pkg/blobfuse-proxy/Dockerfile
- pkg/blobplugin/Dockerfile
update docker image version would also update the kernel version. That could possibly fix #214 and #220 
and also in go.mod we are using the version as 1.16 but the image used for building is still 1.13. Hence updating. 
/kind cleanup
Fixes #
```
none
```
> update docker image version

- Makefile
the below make targets that were added in https://github.com/kubernetes-sigs/blob-csi-driver/pull/395 were not properly cleaned up. So creating a new PR to cleanup those un-used make targets
/kind cleanup
Fixes #
```
none
```
> cleanup un-used to make targets

- pkg/blobfuse-proxy/README.md
- pkg/blobfuse-proxy/rpmbuild/SPECS/utils.spec
/kind feature
**Which issue(s) this PR fixes**: #391 
Fixes #
```
a new RPM package for blobfuse-proxy
```
> create an RPM package for blobfuse-proxy

- pkg/blob/azure.go
- pkg/blob/azure_test.go
- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver.go
- test/e2e/dynamic_provisioning_test.go
- test/utils/blob_log.sh
/kind test
test: add nfs e2e test and also fixed the nfs account dynamic provisioning issue
Fixes #
```
Event initiated by
26f7000f-1d82-44fa-8a55-69c4d5cb1dac
Error code
SubnetsHaveNoServiceEndpointsConfigured
Message
Subnets k8s-subnet of virtual network /subscriptions/xxx/resourceGroups/kubetest-ar68giws/providers/Microsoft.Network/virtualNetworks/k8s-vnet-36253727 do not have ServiceEndpoints for Microsoft.Storage resources configured. Add Microsoft.Storage to subnet's ServiceEndpoints collection before trying to ACL Microsoft.Storage resources to these subnets.
```
- `SubnetsClient.CreateOrUpdate` takes 5min14s sometimes, and …
> test: add nfs e2e test

- docs/csi-debug.md
Cleanup of README
Fixes #
* Added logs comand for multiple pods of daemonset
* Markup with _'''console_ adds "copy" icon - including console output to this block ruins this feature
> Added log for multiple pods command, fexed markup

- deploy/example/nginx-blobfuse-inline-volume.yaml
- pkg/blob/nodeserver.go
/kind bug
fix: only use pod.Namespace in inline volume support
Fixes #
```
none
```
> fix: only use pod.Namespace in inline volume support

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/nodeserver.go
/kind bug
fix: huge storage account list usage
Fixes #289
```
fix: huge storage account list usage
```
> fix: huge storage account list usage

- docs/driver-parameters.md
- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/nodeserver.go
- test/e2e/dynamic_provisioning_test.go
/kind feature
feat: support Azure DataLake account for blobfuse
Fixes #423, #487
```
feat: support Azure DataLake account for blobfuse
```
> feat: support Azure DataLake account for blobfuse

- deploy/blobfuse-proxy/blobfuse-proxy.yaml
/kind feature
feat: add INSTALL_BLOBFUSE env in blobfuse-proxy.yaml
Fixes #
```
none
```
> feat: add INSTALL_BLOBFUSE env in blobfuse-proxy.yaml

- Makefile
- pkg/blob/blob.go
- test/sanity/run-test.sh
/kind feature
feat: add ReadWriteOncePod cap
Fixes #
```
feat: add ReadWriteOncePod cap
```
> feat: add ReadWriteOncePod cap

- docs/driver-parameters.md
- pkg/blob/controllerserver.go
/kind feature
feat: set allowBlobPublicAccess as false by default
Fixes #
```
feat: set allowBlobPublicAccess as false by default
```
> feat: set allowBlobPublicAccess as false by default

- pkg/blob/blob.go
- pkg/blobfuse-proxy/server/server.go
/kind bug
fix: secret namespace searching issue
if node identity does not have permission to list storage account key, it would fail to mount, this PR fixed the issue.
Fixes #
```
I1001 15:34:44.671778       1 utils.go:114] GRPC call: /csi.v1.Node/NodeStageVolume
I1001 15:34:44.671797       1 utils.go:115] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/blob-694-blob.csi.azure.com-preprovsioned-pv-4wzwn/globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":5}},"volume_id":"kubetest-rimgvzsp#fused9a41945a0154b6fbfd#pre-provisioned-multiple-pods1633102415563718032#pre-provi …
```
> fix: secret namespace searching issue

- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- pkg/blob/nodeserver.go
- pkg/csi-common/controllerserver-default.go
- pkg/csi-common/controllerserver-default_test.go
- pkg/csi-common/nodeserver-default.go
- pkg/csi-common/nodeserver-default_test.go
…nimplemented APIs
/kind cleanup
Enable blob csi driver to reuse csicommon implementation for unimplemented APIs
Fixes #
none
```
none
```
> chore: enable blob csi driver to reuse csicommon implementation for unimplemented APIs

- pkg/blob/azure.go
/kind bug
fix: return error earlier when subnetName is empty
Fixes #
```
fix: return error earlier when subnetName is empty
```
> fix: return error earlier when subnetName is empty

- pkg/blobplugin/Dockerfile
- test/e2e/suite_test.go
/kind bug
fix: CVE issues in image build
Fixes #
```
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
| libc-bin    | CVE-2021-33574   | CRITICAL | 2.[31](https://github.com/kubernetes-sigs/blob-csi-driver/runs/5706823026?check_suite_focus=true#step:6:31)-13+deb11u2   | 2.31-13+deb11u3 | glibc: mq_notify does …
```
> fix: CVE issues in image build

- test/external-e2e/run.sh
/kind test
test: run Disruptive external tests
Fixes #
```
none
```
> test: run slow external tests

- Makefile
/kind cleanup
I've been building the driver locally on macbook which does not have `dpkg-deb` installed.
It's been helpful for dev outside linux so I just thought I'd share.
N/A
Fixes #
```
none
```
> chore: allow dpkg-deb to be run via docker

- pkg/blobfuse-proxy/blobfuse-proxy.service
/kind bug
fix: open file num limit setting issue and KillMode in blobfuse-proxy
Fixes #706, #693
<details>
https://manpages.ubuntu.com/manpages/jammy/man5/systemd.kill.5.html
https://www.freedesktop.org/software/systemd/man/systemd.exec.html
```
KillMode=
Specifies how processes of this unit shall be killed. One of control-group, mixed,
process, none.
If set to control-group, all remaining processes in the control group of this unit
will be killed on unit stop (for services: after the stop command is executed, as
configured with ExecStop=). If set to mixed, the SIGTERM signal (see below) is sent to
the main process while the …
```
> fix: open file num limit setting issue and KillMode in blobfuse-proxy

- pkg/csi-common/server_test.go
/kind test
fix TestLogGRPC ut failure
Fixes #
this PR tries to fix the following issue:
```=== RUN   TestLogGRPC
==================
WARNING: DATA RACE
Write at 0x000001d620e0 by goroutine 25:
flag.newBoolValue()
/Users/runner/hostedtoolcache/go/1.19.0/x64/src/flag/flag.go:128 +0x208
flag.(*FlagSet).BoolVar()
/Users/runner/hostedtoolcache/go/1.19.0/x64/src/flag/flag.go:715 +0x214
k8s.io/klog/v2.InitFlags()
/Users/runner/work/azuredisk-csi-driver/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:429 +0x1e6
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.TestLogGRPC()
/Users/runner/work/azuredisk-csi-driver/azuredisk-csi-driver/pkg/csi- …
```
> test: fix TestLogGRPC ut failure

- pkg/csi-common/utils_test.go
- pkg/util/util_test.go
/kind test
Add some coverage to `pkg/util` tests.
Fix a race in csi-common test, described in commit text:
```
Without this fix, running `go test -race -count 10` causes this failure:
/var/folders/py/rwp4m4k977l9stj_f2kqrmxw000_5c/T/go-build3764188957/b001/csi-common.test flag redefined: log_dir
--- FAIL: TestLogGRPC (0.00s)
panic: /var/folders/py/rwp4m4k977l9stj_f2kqrmxw000_5c/T/go-build3764188957/b001/csi-common.test flag redefined: log_dir [recovered]
panic: /var/folders/py/rwp4m4k977l9stj_f2kqrmxw000_5c/T/go-build3764188957/b001/csi-common.test flag redefined: log_dir
goroutine 70 [running]:
testing.tRunner.func1.2({0x17a37e0, 0xc0000b4180})
/usr/local/Cellar/go/1.18.5/libexec/src/testing/testing.go:1389 +0x366 …
```
> fix race in unit test and add some simple tests for utils

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind bug
fix: delete volume failure when management api is throttled
When management api is throttled, this driver would switch to using data plane api to avoid throttling, while if there is account firewall setting, data plane api could not go through firewall, this PR adds a timed cache (10min), default mode would be switched to management api automatically if there is no throttling any more after 10min.
<details>
```
W0905 22:59:33.004209       1 azurefile.go:760] switch to use data plane API instead for account xxx since it's throttled
E0907 11:17:14.978061 1 utils.go:81] GRPC error: rpc error: code = Internal desc = DeleteFileShare pvc-2ce3258a-ef54-4c85-aa6d-7a61ccd48b67 under account(xxx) rg(xxx) failed with …
```
> fix: delete volume failure when management api is throttled

- pkg/blobfuse-proxy/README.md
- pkg/blobfuse-proxy/init.sh
Fixes #
**Testing result:**
**uninstall old version and install new version:**
**reinstall the same driver**
```
none
```
> fix: restart blobfuse proxy when necessary

- pkg/blobfuse-proxy/init.sh
> feat: set read-ahead for nfs mount

- go.mod
- go.sum
- test/utils/azure/azure_helper.go
- vendor/github.com/golang-jwt/jwt/v4/README.md
- vendor/github.com/golang-jwt/jwt/v4/claims.go
- vendor/github.com/golang-jwt/jwt/v4/errors.go
- vendor/github.com/golang-jwt/jwt/v4/map_claims.go
- vendor/github.com/golang-jwt/jwt/v4/parser_option.go
- vendor/github.com/golang-jwt/jwt/v4/token.go
- vendor/github.com/golang-jwt/jwt/v4/types.go
- vendor/github.com/jongio/azidext/go/azidext/LICENSE
- vendor/github.com/jongio/azidext/go/azidext/azure_identity_credential_adapter.go
- vendor/modules.txt
/kind feature
migrate from ADAL to MSAL, since ADAL's EOL is approaching.
Fixes #
```
none
```
> chore: migrate from ADAL lib before its EOL

- deploy/example/e2e_usage.md
- deploy/example/pv-blobfuse-auth.yaml
- deploy/example/pv-blobfuse-csi-keyvault.yaml
- deploy/example/pv-blobfuse-csi.yaml
- deploy/example/pv-blobfuse-nfs.yaml
- docs/driver-parameters.md
doc: refine doc
Fixes #
```
none
```
> doc: refine doc

- pkg/blob/blob.go
- pkg/blob/nodeserver.go
- pkg/blobplugin/main.go
/kind feature
feat: append help link when there is mount error
example mount errors:
```
Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage]
[pod/csi-blob-node-6fqxj/blob] , output: 
[pod/csi-blob-node-6fqxj/blob] Please refer to http://aka.ms/blobmounterror for possible causes and solutions for mount errors.
```
Fixes #
```
feat: append help link when there is mount error
```
> feat: append help link when there is mount error

- .github/workflows/static.yaml
- go.mod
- pkg/blob/controllerserver.go
- pkg/blob/nodeserver.go
tes: fix golint action failure
Fixes #
```
none
```
> tes: fix golint action failure

- pkg/blob/nodeserver.go
- pkg/blobfuse-proxy/server/server.go
/kind bug
fix: add workaround for blobfuse2 mount issue
unlike blobfusev1, blobfuse2 would create a new child process to handle mount, thuse blobfuse mount becomes async now, there would be race condition between real mount process and next bind mount operation if it's async mount, 
this PR would sleep 2s waiting for mount process complete
details: https://github.com/Azure/azure-storage-fuse/issues/1079
Fixes #
also verified manually, after sleep 2s, there is no more mount on local disk any more:
```
blobfuse2 on /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/1f778bb6414796cfefe77ad67ee6e5f21be127ed1adf86affb766488a15eb …
```
> fix: add workaround for blobfuse2 mount race condition issue

- pkg/blob/nodeserver.go
- pkg/blob/nodeserver_test.go
- pkg/blobfuse-proxy/server/server.go
/kind bug
[release-1.20] fix: wait to make sure blobfuse mount complete before bind mount
cherry-pick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/852
Fixes #
```
[release-1.20] fix: wait to make sure blobfuse mount complete before bind mount
```
> [release-1.20] fix: wait to make sure blobfuse mount complete before bind mount

- hack/verify-examples.sh
- pkg/blob/blob.go
- pkg/blob/blob_test.go
/kind feature
feat: support getting sasToken, msiSecret, SPN from secret
This PR could support reading sasToken, msiSecret, SPN from inline volume
Fixes #840, #863
```
feat: support getting sasToken, msiSecret, SPN from secret
```
> fix: support getting sasToken, msiSecret, SPN from secret

- pkg/blobfuse-proxy/init.sh
- pkg/blobplugin/Dockerfile
Fixes #
1. fuse and fuse3 can't be installed at the same time: `fuse3 : Breaks: fuse`
2. blobfuse returned error `error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory` after using 18.04 packages-microsoft-prod.deb package to install blobfuse on ubuntu 22.04
3. blobfuse2 returned error `error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory` after using 18.04 packages-microsoft-prod.deb package to install blobfuse2 on ubuntu 22.04
4. mariner os can't use apt-get to install package
```
none
```
> fix: install blobfuse package issue in blobfuse-proxy initContainer

- test/external-e2e/run.sh
/kind cleanup
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
```
none
```
> fix: use dl.k8s.io, not kubernetes-release bucket

- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind bug
fix: dynamic provisioning support with blobfuse msi auth
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/954
Fixes #
```
fix: dynamic provisioning support with blobfuse msi auth
```
> [release-1.21] fix: dynamic provisioning support with blobfuse msi auth

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/nodeserver.go
- pkg/blobplugin/main.go
/kind bug
fix: add VolumeStats cache to avoid massive statfs calls
This PR adds a 10min cache for VolumeStats per volumeID, that could avoid massive statfs calls
Fixes #
```
fix: add VolumeStats cache to avoid massive statfs calls
```
> fix: add VolumeStats cache to avoid massive statfs calls

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/nodeserver.go
/kind bug
fix: add VolumeStats cache to avoid massive statfs calls
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1016
Fixes #
```
fix: add VolumeStats cache to avoid massive statfs calls
```
> [release-1.21] fix: add VolumeStats cache to avoid massive statfs calls

- deploy/example/e2e_usage.md
doc: refine inline volume example
Fixes #1022
```
none
```
> doc: refine inline volume example

- .github/workflows/linux.yaml
- hack/verify-helm-chart.sh
test: fix verify-helm-chart failure
```
helm chart index verified.
Running helm lint
==> Linting /home/prow/go/src/sigs.k8s.io/blob-csi-driver/charts/latest/blob-csi-driver
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
Comparing image version between helm chart and manifests in deploy folder
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. …
```
> test: fix verify-helm-chart failure

- hack/verify-examples.sh
- test/external-e2e/testdriver-blobfuse.yaml
- test/external-e2e/testdriver-nfs.yaml
- test/utils/blob_log.sh
/kind test
test: adjust log print in e2e test
Fixes #
```
none
```
> test: adjust log print in e2e test

- pkg/blob/azure.go
/kind bug
fix: nfs volume creation failure due to Microsoft.Storage.Global Service endpoint enabled
- error msg
```
35s         Warning   ProvisioningFailed      persistentvolumeclaim/pvc-azurefile   failed to provision volume with StorageClass "azurefile-nfs": rpc error: code = Internal desc = update service endpoints failed with error: failed to update the subnet aks-subnet under vnet aks-vnet-32454943: &{false 400 0001-01-01 00:00:00 +0000 UTC {
"error": {
"code": "SubnetHasBothRegionalAndGlobalStorageServiceEndpointsTogether",
"message": "Subnet /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/aks-vnet-32454943/subnets/aks-subnet has ServiceEndpoint entries for both …
```
> fix: nfs volume creation failure due to Microsoft.Storage.Global Service endpoint enabled

- pkg/blob/azure.go
- pkg/blob/azure_test.go
- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver_test.go
- pkg/blobplugin/main.go
- test/e2e/suite_test.go
/kind cleanup
adopt dependency injection pattern and extract cloud property from driver factory
Fixes #
```
none
```
> Refactor: adopt dependency injection pattern and extract cloud property

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver.go
- pkg/blob/nodeserver.go
/kind bug
fix: make aznfs protocol consistent with nfs
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1103
Fixes #
```
fix: make aznfs protocol consistent with nfs
```
> [release-1.22] fix: make aznfs protocol consistent with nfs

- docs/csi-debug.md
doc: add aznfs mount helper tsg
Fixes #
```
doc: add aznfs mount helper tsg
```
> doc: add aznfs mount helper tsg

- charts/README.md
- deploy/blobfuse-proxy/README.md
- docs/install-csi-driver-master.md
doc: update blobfuse-proxy support on coreos
Fixes #1114
```
none
```
> doc: update blobfuse-proxy support on coreos

- README.md
- deploy/example/cloning/README.md
- deploy/example/cloning/nginx-pod-restored-cloning.yaml
- deploy/example/cloning/pvc-blob-csi-cloning.yaml
- hack/verify-yamllint.sh
doc: add volume cloning doc
Fixes #
```
none
```
> doc: add volume cloning doc

- deploy/csi-blob-node.yaml
/kind cleanup
chore: support installing blob-csi-driver with aznfs-mount by install-driver.sh
Fixes #
```
chore: support installing blob-csi-driver with aznfs-mount by install-driver.sh
```
> chore: support installing blob-csi-driver with aznfs-mount by install-driver.sh

- pkg/blobplugin/Dockerfile
/kind feature
feat: upgrade to aznfs 2.0.0 version for nfs mount
Fixes #
```
feat: upgrade to aznfs 2.0.0 version for nfs mount
```
> feat: upgrade to aznfs 2.0.0 version for nfs mount

- pkg/blob/azure.go
- pkg/blob/azure_test.go
- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver_test.go
- pkg/blobplugin/main.go
- pkg/util/util.go
- pkg/util/util_test.go
- test/e2e/suite_test.go
/kind cleanup
Refactor: Extract kubeclient from cloud provider
Fixes #
```
none
```
> Refactor: Extract kubeclient from cloud provider

- pkg/blob/nodeserver.go
- pkg/blob/nodeserver_test.go
/kind bug
fix: reduce mount lock to avoid volumeID collision issue
the volumeHandle(volumeID) could be duplicated in PV, and duplicated volumeHandle(volumeID) is already allowed in latest k8s version, this PR reduces mount lock to avoid volumeID collision issue, the lock only happen when volumeID + stagingPath is the same
Fixes #
```
fix: reduce mount lock to avoid volumeID collision issue
```
> fix: reduce mount lock to avoid volumeID collision issue

- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind bug
fix: generate sas token when secret is used in volume cloning
Fixes #
```
fix: only generate sas token when secret is used in volume cloning
```
> fix: generate sas token when secret is used in volume cloning

- pkg/blob/azure.go
- pkg/blob/azure_test.go
- pkg/blob/controllerserver.go
- pkg/blob/nodeserver.go
/kind bug
fix: panic when controller does not have cloud config
Fixes #
```
fix: panic when controller does not have cloud config
```
> fix: panic when controller does not have cloud config

- docs/driver-parameters.md
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind feature
feat: allow multiple subnets in updating service endpoints
Fixes #1606
```
feat: allow multiple subnets in updating service endpoints
```
> feat: allow multiple subnets in updating service endpoints

- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- pkg/blob/volume_lock.go
- pkg/util/util.go
- pkg/util/util_test.go
/kind bug
fix: fix azcopy exec timeout func, use WaitForExecCompletion func in util.go waits for the exec function to complete or times out
Fixes #
```
none
```
> fix: fix azcopy exec timeout func

- pkg/csi-common/utils.go
- pkg/csi-common/utils_test.go
/kind cleanup
strip service account token to avoid security risk.
Fixes #
```
fix: strip service account token
```
> fix: strip service account token

- docs/workload-identity-static-pv-mount.md
> chore: fix workload identity docs

- docs/driver-parameters.md
doc: deprecate AzureStorageIdentityObjectID field
from blobfuse 2.3.0, AzureStorageIdentityObjectID relies on azure cli installed on the node, pls use 
AzureStorageIdentityClientID or 
AzureStorageIdentityResourceID parameter instead.
CX needed to install Azure CLI on worker nodes manually.
With this PR, ObjectID (Managed Identity Authentication) now relies on the azure cli.
https://github.com/Azure/azure-storage-fuse/commit/644728f2093e2a45914a294c64febbcdb5ffc866#diff-b7b39483e2bf51ebe17ba7827a1b18cbaf75b74fcfe0796ae7a2d3e667b45289R95
```
volumeAttributes:.
AzureStorageAuthType: msi
AzureStorageIdentityObjectID: XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```
Every time CX reimages a worker node with …
> doc: deprecate AzureStorageIdentityObjectID field

- deploy/example/blobfuse-mi/README.md
- deploy/example/blobfuse-mi/pv-blobfuse-mi.yaml
- deploy/example/blobfuse-mi/storageclass-blobfuse-mi.yaml
doc: add mount azure blob storage doc
referring to https://github.com/qxsch/Azure-Aks/tree/master/aks-blobfuse-mi
Fixes #
```
none
```
> doc: add blobfuse mount with managed identity doc

- docs/driver-parameters.md
- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- test/e2e/dynamic_provisioning_test.go
/kind feature
Allows to provision dynamic storage accounts with shared key access disabled.
Fixes #1462.
Tested on AKS cluster by mounting dynamic PVC to a pod and writing a file.
Storage class spec:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: azureblob-fuse
reclaimPolicy: Delete
volumeBindingMode: Immediate
provisioner: blob.csi.azure.com
allowVolumeExpansion: true
parameters:
skuName: Premium_LRS
allowSharedKeyAccess: "false"
storeAccountKey: "false"
AzureStorageAuthType: msi
AzureStorageIdentityClientID: <redacted>
```
```
none
```
> feat: add allowSharedKeyAccess parameter

- deploy/example/blobfuse-mi/pv-blobfuse-mi.yaml
- deploy/example/blobfuse-mi/storageclass-blobfuse-mi.yaml
- hack/verify-yamllint.sh
add check
doc: add yamllint check
Fixes #
```
none
```
> doc: add yamllint check

- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind bug
`CreateVolume()` now follows the established volume provisioning logic when cloning volume content.
This ensures the created volume has the expected configuration, metadata and content.
- Resolves issue #1495
- Prevents SAS tokens from being logged in clear text during volume cloning
- Avoids duplication of azcopy jobs when `containerName` or `containerNamePrefix` are specified
- Volumes are now provisioned correctly when cloning
> fix: clone volume content to requested volume

- pkg/blob/controllerserver.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
/kind bug
fix: volume cloning between different storage account for BlobAccessTierNotSupportedForAccountType error
azcopy between different storage account has this issue:
referring to https://github.com/Azure/azure-storage-azcopy/issues/327 to fix
Also in this issue comment: https://github.com/Azure/azure-storage-azcopy/issues/327#issuecomment-481824121, azcopy may automatically replicate the source blob's tier info to the destination, so create blob container before azcopy instead of using azcopy to create container is more correct.
add volume cloning between different account e2e test
Fixes #
```
none
```
> fix: volume cloning between different storage account for BlobAccessTierNotSupportedForAccountType error

- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind cleanup
cleanup: refactor volume cloning 
Fixes #
```
none
```
> cleanup: refactor volume cloning 

- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- pkg/blob/volume_lock.go
- pkg/util/util.go
- pkg/util/util_test.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
/kind bug
[release-1.23] fix: clone volume content to requested volume
[release-1.23] fix: volume cloning between different storage account for BlobAccessTierNotSupportedForAccountType error
cherry-pick for https://github.com/kubernetes-sigs/blob-csi-driver/pull/1504 and https://github.com/kubernetes-sigs/blob-csi-driver/pull/1517
Fixes #
```
none
```
> [release-1.23] fix: clone volume content to requested volume

- pkg/blob/controllerserver.go
/kind bug
fix: only last subnet is set in account ACL created by driver
When `subnetName` is specified in storage class, currently only last subnet is set in account ACL created by driver, this PR fixed the issue.
Fixes #
```
fix: only last subnet is set in account ACL created by driver
```
> fix: only last subnet is set in account ACL created by driver

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/nodeserver.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/testsuites/specs.go
- test/e2e/testsuites/testsuites.go
/kind bug
fix: respect ReadOnly AccessMode in volume mount
When user sets ReadOnlyMany or ReadOnlyOnce on the volume accessmode, the driver should append "ro" mount option during mount
Fixes #
```
fix: respect ReadOnly AccessMode in volume mount
```
> fix: respect ReadOnly AccessMode in volume mount 

- deploy/example/cloning/README.md
doc: improve volume cloning doc
Fixes #
```
none
```
> doc: improve volume cloning doc

- pkg/blob/azure.go
- pkg/blob/azure_test.go
- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver.go
/kind bug
fix: nfs mount failure when there are multiple subnets in the cluster
When there are multiple node pools (with multiple subnets) in the cluster, this driver would only set the first node pool to storage account ACL, which makes nfs mount fails with "access denied" error when pods with nfs volume are scheduled to other node pool, this PR adds multiple subnets into the account ACL.
Fixes #
```
fix: nfs mount failure when there are multiple subnets in the cluster
```
> fix: nfs mount failure when there are multiple subnets in the cluster

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
/kind bug
fix: VirtualNetworkRule match issue during account search
related to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6741
original code logic does not check every VirtualNetworkResourceID in the account, thus the matching is incomplete, this PR fixes the issue.
Fixes #
```release-note
fix: VirtualNetworkRule match issue during account search
```
```docs
fix: VirtualNetworkRule match issue during account search
```
> fix: VirtualNetworkRule match issue during account search

- pkg/blob/controllerserver.go
/kind bug
fix: volume cloning sas token logged
Fixes #
```
none
```
> fix: volume cloning sas token logged

- pkg/blob/azure.go
- pkg/blob/azure_test.go
- pkg/blob/controllerserver.go
- test/e2e/testsuites/testsuites.go
- test/utils/azure/authorization_helper.go
> chore: Replace deprecated k8s.io/utils/pointer with k8s.io/utils/ptr

- deploy/example/storageclass-blob-nfs.yaml
- deploy/example/storageclass-blobfuse.yaml
- deploy/example/storageclass-blobfuse2.yaml
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- test/e2e/dynamic_provisioning_test.go
- test/external-e2e/run.sh
/kind bug
fix: add fallback to sas token on azcopy copy command
when cx only give `Storage Blob Data Reader` role, azcopy list command will succeed, add fallback to sas token on azcopy copy command when occured AuthorizationPermissionMismatch error
Fixes #
```
none
```
> fix: add fallback to sas token on azcopy copy command

- deploy/example/storageclass-blob-nfs.yaml
- deploy/example/storageclass-blobfuse.yaml
- deploy/example/storageclass-blobfuse2.yaml
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- test/e2e/dynamic_provisioning_test.go
- test/external-e2e/run.sh
/kind bug
fix: add fallback to sas token on azcopy copy command
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1564
Fixes #
```
fix: add fallback to sas token on azcopy copy command
```
> [release-1.23] fix: add fallback to sas token on azcopy copy command

- deploy/example/e2e_usage.md
doc: update inline volume doc
Fixes #2098
```
none
```
> doc: update inline volume doc

- .github/workflows/static.yaml
- hack/verify-golint.sh
- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- pkg/blob/nodeserver.go
- pkg/csi-common/utils.go
- pkg/csi-common/utils_test.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/suite_test.go
> [release-1.23] cleanup: upgrade golint version and fix golint errors

- pkg/blobplugin/Dockerfile
/kind feature
Installs blobfuse2 for arm64 build of the blobplugin docker image. Needed to support using fuse2 protocol on arm64.
Fixes #1618
```
none
```
> feat: install blobfuse2 for arm64

- deploy/example/e2e_usage.md
- deploy/example/pv-blobfuse-auth.yaml
- deploy/example/pv-blobfuse-csi-keyvault.yaml
- deploy/example/pv-blobfuse-csi.yaml
- deploy/example/pv-blobfuse-nfs.yaml
- docs/driver-parameters.md
- docs/workload-identity-static-pv-mount.md
doc: remove obsolete doc about volumeID format
Fixes #1619
```
none
```
> doc: remove obsolete doc about volumeID format

- pkg/blob/nodeserver.go
/kind bug
fix: change mount timeout to 1.5min
Previous set mount timeout in csi as 2 min, which will cause context deadline error but not csi timeout error. Change mount timeout to 1.5 minutes
Details:
the k8s kubelet have 2min timeout for every mount, and we have set 2min timeout inside csi driver(that actually costs 2min+ totally for the whole mount process), and when the outer timeout is triggered by k8s kubelet, it would make another MountDevice call, while at that time, the previous mount is still in progress, thus the second mount would never work until in the inner CSI driver mount timeout.
Fixes #
```
none …
```
> fix: change mount timeout to 1.5min

- deploy/example/nfs/README.md
- deploy/example/pv-blobfuse-nfs.yaml
- deploy/example/storageclass-blob-nfs.yaml
doc: Azure Linux node does not support nconnect option
you could get following nfs mount error on Azure Linux node:
```
Warning  FailedMount       26s (x8 over 90s)  kubelet            MountVolume.MountDevice failed for volume "pvc-b4bb90f5-0ab5-4861-88b1-f983b7d22b99" : rpc error: code = Internal desc = volume(MC_andy-aks129_andy-aks129_eastus2#nfs40fc7f659b604080af74#pvc-b4bb90f5-0ab5-4861-88b1-f983b7d22b99##default#) mount "nfs40fc7f659b604080af74.blob.core.windows.net:/nfs40fc7f659b604080af74/pvc-b4bb90f5-0ab5-4861-88b1-f983b7d22b99" on "/var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/841ce093838cb0710d083145a4b3fb2c559989d43d6964e8efe6cea838e324b4/globalmount" failed with mount …
```
> doc: Azure Linux node does not support nconnect option

- pkg/util/util.go
- pkg/util/util_test.go
fix
/kind test
test: add unit test
Fixes #
```
none
```
> test: add unit test

- .github/workflows/linux.yaml
/kind test
test: exclude some go fake files in ut coverage
Fixes #
```
none
```
> test: exclude some go fake files in ut coverage

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
- vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
- vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_publicip_repo.go
- vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
/kind bug
fix: incorrect cloud provider setting in sovereign cloud
related to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8504
the cloud provider with track2 sdk does not work in Azure China cloud, error is like following:
```
E0304 04:59:58.032152       1 utils.go:110] GRPC error: rpc error: code = Internal desc = ManagedIdentityCredential authentication failed. the requested identity isn't assigned to this resource
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
--------------------------------------------------------------------------------
{
"error": "invalid_resource",
"error_description": "AADSTS500011: The resource principal named …
```
> fix: incorrect cloud provider setting in sovereign cloud

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go
/kind bug
fix: account match algorithm when source account name is provided, this is used in volume clone and snapshot restore scenarios, related to fix: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8560
<details>
```
I0306 12:52:31.840777       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0306 12:52:31.840801       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-23e65b01-80b4-4c71-8f42-1fe6fccbd64b","parameters":{"csi.storage.k8s.io/pv/name":"pvc-23e65b01-80b4-4c71-8f42-1fe6fccbd64b","csi.storage.k8s.io/pvc/name":"afspvc","csi.storage.k8s.io/pvc/namespace":"choudharypr-test-target","skuName":"Standard_LRS"},"volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["mfsymlinks","actimeo=30","nosharesock"]}},"acces …
```
> fix: account match algorithm when source account name is provided

- docs/workload-identity-static-pv-mount.md
- pkg/blob/blob.go
/kind feature
The previous implementation of supporting workload identity is to use workload identity to retrieve account key for mounting. Since blobfuse2 has supported workload identity authentication, we can use workload identity to directly mount without retrieving account key.
Fixes #
```
feat: support original workload identity for blobfuse2 (without retrieve account key)
```
> feat: support workload identity

- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
/kind bug
fix: allow clientID, tenantID workload identity parameters in storage class
Fixes #
```
none
```
> fix: allow clientID, tenantID workload identity parameters in storage class

- pkg/blob/blob.go
- pkg/blob/blob_test.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- test/e2e/dynamic_provisioning_test.go
/kind feature
feat: add VNetLinkName and PublicNetworkAccess in account creation
cherrypick of https://github.com/kubernetes-sigs/blob-csi-driver/pull/1983
Fixes #
```
feat: add VNetLinkName and PublicNetworkAccess in account creation
```
> [release-1.26] feat: add VNetLinkName and PublicNetworkAccess in account creation

- docs/driver-parameters.md
doc: update tips for fsGroupChangePolicy parameter setting
Fixes #
```
none
```
> doc: update tips for fsGroupChangePolicy parameter setting

- pkg/blob/blob.go
- pkg/blob/blob_test.go
/kind bug
If the volumeattributes.mountpermissions are set for an nfs volume, we check if the permissions on the mount targetPath are the same as the expected mountPermissions. When this check is made currently, the targetPath mode bits are masked to use only the permission bits.
We should do the same with the mountPermissions bits to ensure that there isn't an unnecessary mismatch.
After the comparison, if the mount permissions are different, this PR ensures that only mount permissions change with the chmod operation and the rest of the bits like gid remain as is.
Related PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2600
Fixes #
**Special notes for …
> fix: only use the permission bits for chmod

- pkg/blob/nodeserver.go
/kind cleanup
cleanup: fix incorrect logging info when volume is already mounted
Fixes #
<details>
```
I0715 13:56:59.303034    5226 utils.go:104] GRPC call: /csi.v1.Node/NodePublishVolume
I0715 13:56:59.303059    5226 utils.go:105] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/2f2914cc953e7e7b220e3e0426a57d4a467e8318328dd52fc51b26265bea50f7/globalmount","target_path":"/var/lib/kubelet/pods/ab987be3-90c7-48f9-a861-7e522cfb07d6/volumes/kubernetes.io~csi/pvc-8507f388-e9c3-4635-a0e1-dbc980fd9294/mount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["-o …
```
> cleanup: fix incorrect logging info when volume is already mounted

- pkg/blobfuse-proxy/install-proxy.sh
Reverts kubernetes-sigs/blob-csi-driver#1508
we could revert now since https://github.com/kubernetes-sigs/blob-csi-driver/pull/2089 could fix the issue more gracefully.
Fixes #2098
> Revert "fix: ignore specific blobfuse version install failure"

- pkg/blob/blob.go
- pkg/blob/controllerserver.go
- pkg/blob/controllerserver_test.go
- pkg/blob/nodeserver.go
- test/e2e/dynamic_provisioning_test.go
/kind feature
feat: support blobStorageAccountType parameter in storage class or pv
usually we don't need this parameter setting in sc or pv since from blobfuse 2.4.2, the blobfuse2 driver would auto detect storage account type, while if user still wants to specify this account type in edge case, this PR will support this scenario:
```
AZURE_STORAGE_ACCOUNT_TYPE: Specifies the account type 'block' or 'adls'
```
Fixes #
```
feat: support blobStorageAccountType parameter in storage class or pv
```
> feat: support blobStorageAccountType parameter in storage class or pv

- deploy/blobfuse-proxy/README.md
doc: fix outdated doc
Fixes #2112
```
none
```
> doc: fix outdated doc

- pkg/blobfuse-proxy/server/server.go
/kind cleanup
cleanup: add more logging in blobfuse-proxy when blobfuse2 not found
Fixes #
```
none
```
> cleanup: add more logging in blobfuse-proxy when blobfuse2 not found

- hack/verify-helm-chart-index.sh
test: refine verify-helm-chart-index.sh
Fixes #
```
none
```
> test: refine verify-helm-chart-index.sh

- pkg/blobfuse-proxy/init.sh
- pkg/blobfuse-proxy/server/server.go
/kind bug
fix: blobfuse-proxy install on OpenShift 4.19
Fixes #2192
```
fix: blobfuse-proxy install on OpenShift 4.19
```
> fix: blobfuse-proxy install on OpenShift 4.19
